// Optional synthetic answer-transition profiler. Requires Playwright; never opens an Anki profile.
const {chromium}=require('playwright');
const fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..');
let source=fs.readFileSync(path.join(root,'web/overlay.js'),'utf8');
source=source.replace('  function drawPrismGate(renderer, now) {',`  function drawPrismGate(renderer, now) {
  const start=performance.now(), before=window.probeFrames.length;
  const deadline=renderer.nextFrameAt;
  try {return measuredDraw(renderer,now)} finally {window.probeCalls.push({at:start,duration:performance.now()-start,drew:window.probeFrames.length>before,deadline,now,age:renderer.clock-renderer.eventAt});}
  }
  function measuredDraw(renderer, now) {`);
source=source.replace('  function render(data) {', '  function render(data) {const start=performance.now();try{return measuredRender(data)}finally{window.probeRenders.push(performance.now()-start)}} function measuredRender(data) {');
const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0])); if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(f.endsWith('web'+path.sep+'overlay.js')?source:fs.readFileSync(f));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage({viewport:{width:390,height:820},deviceScaleFactor:2});await page.addInitScript(()=>{window.probeRenders=[];window.probeFrames=[];window.probeCalls=[];window.probeLong=[];new PerformanceObserver(l=>probeLong.push(...l.getEntries().map(x=>({start:x.startTime,duration:x.duration})))).observe({entryTypes:['longtask']});const fill=CanvasRenderingContext2D.prototype.fillRect;CanvasRenderingContext2D.prototype.fillRect=function(x,y,w,h){if(this.canvas.id==='acgPrismCanvas'&&x===0&&y===0)probeFrames.push(performance.now());return fill.call(this,x,y,w,h)};});
const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await page.goto(`http://127.0.0.1:${server.address().port}/tests/prism_gate_harness.html`);await page.waitForTimeout(1000);const events=[];
const starts=process.env.HYPERNOVA_PROGRESSION ? [1,9,12,19,29,49,99] : [120,121,122,123,124,125];
for(let i=0;i<starts.length;i++){const at=await page.evaluate(([i,start])=>{const at=performance.now();const now=Date.now();updateDemoState({scoreboardLayout:'best_only',runHistory:{bestStreak:500,savedBestStreak:500,active:{streak:start},runs:Array.from({length:5},(_,k)=>({id:k,streak:500-k,endedAt:'2026-09-08T12:30:00'}))},streak:start,satelliteColors:Array(Math.min(100,start)).fill('green'),phase:'question',phaseStartEpochMs:now,phaseLimitMs:12000,phaseBaseLimitMs:12000,timerDisplayRemainingMs:12000,timerDisplayNowEpochMs:now});demoEvent(['hard','good','easy'][i%3]);return at;},[i,starts[i]]);events.push(at);await page.waitForTimeout(2100);}
const result=await page.evaluate(events=>({events,frames:probeFrames,calls:probeCalls,longTasks:probeLong,renderDurations:probeRenders}),events);result.startingStreaks=starts;fs.writeFileSync(path.join(root,process.env.HYPERNOVA_PROGRESSION?'tests/hypernova-progression-answer-trace.json':'tests/hypernova-answer-trace.json'),JSON.stringify(result));
for(const at of events){const calls=result.calls.filter(x=>x.at>=at&&x.at<at+2000);const frames=result.frames.filter(x=>x>=at&&x<at+2000);const gaps=frames.slice(1).map((x,i)=>({gap:x-frames[i],age:(x-at)/1000}));console.log(JSON.stringify({worst:gaps.sort((a,b)=>b.gap-a.gap).slice(0,3),maxDrawMs:Math.max(...calls.map(x=>x.duration)),skips:calls.filter(x=>!x.drew).map(x=>({age:x.age,early:x.deadline-x.now}))}));}console.log('Render durations:',JSON.stringify(result.renderDurations));console.log('Long tasks:',JSON.stringify(result.longTasks));
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
