"""Build the reviewed first eight daily quiz files. Run from any directory."""
import json
from pathlib import Path
from export_quizduel import build_exports

ROOT = Path(__file__).resolve().parent

# Each item is: verse reference, explanation, then Kid / High School / Expert.
# A question row has a focused stem, the best answer, and three nearby distractors.
BANK = {}

def day(date, rows):
    assert len(rows) == 10, (date, len(rows))
    BANK[date] = rows

day('2026-09-27', [
 ('30:10-11', 'The people asked prophets for pleasant messages instead of truthful ones.',
  'What kind of message did the people ask the prophets to give?|Pleasant words even if untrue|Warnings that called them to change|News about the coming harvest|Songs for their worship',
  'Why was the request for “smooth things” a problem?|It put comfort ahead of truth|It made prophecy too difficult to hear|It asked prophets to speak in poetry|It focused on distant events',
  'What is the central failure in the people’s instruction to their seers?|They tried to control revelation to avoid correction|They confused prophetic warnings with royal commands|They assumed judgment could only concern other nations|They treated a symbolic vision as a literal report'),
 ('30:13-14', 'Isaiah compares the consequences of rejected counsel to a wall that collapses and a vessel shattered beyond use.',
  'What happens to the wall in Isaiah’s warning?|It breaks suddenly|It becomes a gate|It is painted white|It grows taller',
  'What do the broken wall and shattered pot together emphasize?|A hidden weakness can end in total collapse|A strong wall can protect a fragile vessel|A clay pot can be repaired more easily than a wall|A warning matters only after visible damage',
  'Why pair a swelling breach with a vessel broken into unusable pieces?|The images move from delayed instability to irreversible ruin|The images contrast public danger with private safety|The images show that only the vessel, not the wall, was flawed|The images distinguish political defeat from spiritual renewal'),
 ('30:15-16', 'The Lord offered salvation in returning, rest, quietness, and trust; the people chose flight on horses.',
  'What did the Lord say would give His people strength?|Quiet trust in Him|Faster horses|Larger walls|More weapons',
  'How does the people’s answer about horses oppose the Lord’s offer?|They choose frantic escape instead of trusting return|They choose travel instead of staying in one city|They choose human teachers instead of prophets|They choose farming instead of fighting',
  'What irony shapes the response to “we will flee upon horses”?|Their chosen speed becomes the speed of their pursuers|Their horses become the means of their return|Their trust in horses brings the promised rest|Their flight reveals that the threat was imaginary'),
 ('30:18-19', 'The Lord waits to show mercy and promises to answer when the people cry to Him.',
  'What does the Lord promise to do when His people cry to Him?|Answer them|Hide from them|Send them away|Ask for payment',
  'What does the Lord’s waiting in verse 18 reveal beside His judgment?|He still intends to show mercy|He has forgotten the people|He needs time to gain strength|He withdraws every promise',
  'How does the Lord’s waiting reframe the preceding warning of collapse?|Judgment does not cancel His readiness to be gracious|Delay proves the danger was overstated|Mercy removes any need for the people to return|The warning was addressed only to foreign nations'),
 ('30:20-21', 'Even amid adversity, the people are promised visible teachers and guidance on which way to walk.',
  'What does the guiding voice tell the people?|This is the way; walk in it|Build a higher tower|Wait for a faster horse|Stop listening to teachers',
  'What changes when the people can see their teachers and hear “This is the way”?|Guidance becomes available during hardship|Hardship ends before anyone can learn|Teachers replace every personal choice|Only one road remains physically open',
  'How do “bread of adversity” and a guiding voice work together?|Hardship remains, but instruction becomes accessible within it|Instruction is delayed until hardship has fully ended|Adversity proves the teachers were unreliable|The voice offers a shortcut around every consequence'),
 ('30:22', 'The restored people reject their silver and gold images rather than continuing to honor them.',
  'What do the people do with their idols?|Throw them away|Carry them to Zion|Cover them with more gold|Ask them for rain',
  'What action shows a real change of allegiance in verse 22?|Casting away once-valued images|Repairing damaged images|Moving images to a safer place|Keeping images as a backup',
  'Why mention precious silver and gold coverings when describing the idols’ rejection?|Costly appearance cannot make a false object worthy of trust|Precious metal had been the only source of the people’s sin|The images become acceptable once their coverings are removed|The coverings are offered as payment for rain'),
 ('30:23-26', 'The promised rain, abundant food, streams, and healing portray restoration after hardship.',
  'What does the Lord promise for planted seeds?|Rain and abundant food|A sudden wall collapse|A long drought|A new idol',
  'How do rain and the healing of a wound belong to the same promise?|Both portray the Lord restoring life after loss|Rain is a warning while healing is a punishment|Both describe the people’s military strength|Healing occurs only if rain stops',
  'What unifies the agricultural abundance and intensified light in this passage?|Creation imagery conveys a far-reaching act of divine healing|The images give a precise timetable for farming|The images praise the people’s new technology|The abundance cancels the passage’s call to return'),
 ('35:1-2', 'Isaiah pictures a desert rejoicing and blossoming as part of the Lord’s renewing work.',
  'What happens to the desert in Isaiah 35?|It blossoms and rejoices|It becomes a city|It freezes over|It disappears beneath the sea',
  'What does a blossoming wilderness suggest in this chapter?|A place of loss becomes a place of life|A place of safety becomes dangerous|A royal garden needs new workers|The people must abandon every dry place',
  'How does the wilderness imagery answer the earlier vision of judgment?|The scene of barrenness becomes a sign of restored glory|The desert remains barren while Zion alone changes|The image shifts attention from God to human cultivation|The blooming scene denies that judgment ever occurred'),
 ('35:3-6', 'The fearful are told to be strong because God comes to save; healing images follow.',
  'What message should be given to people with fearful hearts?|Be strong; God will save|Hide until the harvest|Make your own path alone|Give up on the journey',
  'How do the healings in verses 5–6 support the call to courage?|They picture God removing barriers that seemed fixed|They show that fear is the only real problem|They make human help unnecessary|They describe a new military campaign',
  'What is the rhetorical role of opened eyes, unstopped ears, and leaping limbs?|Concrete reversals make the promised salvation imaginable|They narrow the promise to three medical cases|They explain why the people first rejected the prophets|They replace the earlier command to strengthen the fearful'),
 ('35:8-10', 'The redeemed travel the way of holiness to Zion, where joy replaces sorrow.',
  'Where do the redeemed people travel on the holy road?|To Zion|To Babylon|To the desert alone|To a foreign throne',
  'What makes the highway more than an ordinary road?|It represents a safe return for the redeemed|It is wide enough for every army|It avoids every hill and valley|It leads to a new trading city',
  'How do the safe highway and vanishing sorrow complete the chapter’s movement?|They turn restoration into a secure return and lasting joy|They replace the need for holiness with a shorter route|They show that the journey matters more than its destination|They make hope depend on the travelers’ own strength'),
])

day('2026-09-28', [
 ('40:1-2', 'The opening command is to comfort Jerusalem and announce that her hard service and guilt have reached an end.',
  'What message opens Isaiah 40?|Comfort God’s people|Prepare for a siege|Build a new idol|Gather more weapons',
  'Why does the message to Jerusalem sound different from a warning of judgment?|It announces comfort and pardon after hardship|It asks Jerusalem to deny earlier wrongs|It says Babylon has become the new covenant people|It praises Jerusalem for avoiding every consequence',
  'What gives the repeated command to “comfort” its force in the opening verses?|A prior period of suffering is now met by announced pardon|The speaker changes from prophet to foreign ruler|The people are asked to comfort God for His loss|The city has escaped any need for reconciliation'),
 ('40:3-5', 'The prepared highway and leveled terrain picture readiness for the Lord’s revealed glory.',
  'What should be prepared in the wilderness?|A way for the Lord|A hiding place for idols|A pasture for horses|A wall around Babylon',
  'What do raised valleys and lowered mountains communicate?|Obstacles are removed for the Lord’s coming|The people must reshape every landscape themselves|The Lord can appear only on level land|The old cities must be rebuilt first',
  'How do the road image and the claim that “all flesh” will see glory relate?|Preparation leads to a public revelation beyond one location|The road limits the revelation to those who travel it|The terrain changes replace the Lord’s arrival|The announcement is addressed only to mountain dwellers'),
 ('40:6-8', 'Human life is compared to fading grass, while God’s word stands forever.',
  'What lasts after grass and flowers fade?|God’s word|Human beauty|A ruler’s promise|A carved image',
  'What contrast does Isaiah draw between people and God’s word?|Human life is brief; God’s word endures|People are strong; God’s word is fragile|Both fade in the same season|Neither can survive hardship',
  'Why is the grass comparison apt in a chapter of comfort?|It shifts confidence from fragile human power to God’s enduring promise|It proves the comfort was intended only for farmers|It makes the coming glory dependent on human longevity|It describes the permanence of Babylon’s rule'),
 ('40:9-11', 'The announced God is both powerful in rule and gentle toward His flock.',
  'How does the Lord carry the lambs?|In His arms|On a horse|In a cart|Across a bridge',
  'Which pair best captures the portrait of the Lord in verses 10–11?|Strong ruler and gentle shepherd|Distant judge and silent witness|Weary traveler and frightened sheep|Hidden maker and powerless king',
  'What is gained by placing the ruling arm beside the arm that gathers lambs?|Divine strength is shown as compatible with tender care|The shepherd image corrects a mistaken claim of divine power|The ruling arm belongs to a different speaker|Tenderness is shown as a reward for the strongest sheep'),
 ('40:12-17', 'The measuring questions and comparison to a drop of water place nations within the scale of God’s power.',
  'How does Isaiah compare the nations to God?|Like a drop in a bucket|Like a mountain over Him|Like a flock He fears|Like stars He cannot count',
  'What is the point of asking who measured the waters and weighed the mountains?|To show the Creator exceeds human and national power|To teach a method for surveying land|To praise the largest nation|To suggest creation was a difficult accident',
  'How do the measurement questions prepare for the “drop of a bucket” comparison?|They establish the Creator’s scale before relativizing nations|They imply God needs nations to complete creation|They rank different nations by their size|They turn the passage into a lesson about weights'),
 ('40:18-20', 'Isaiah contrasts the incomparable God with images made and stabilized by craftsmen.',
  'Who makes the carved image in Isaiah’s example?|A craftsperson|The Lord|A shepherd|A prophet',
  'Why is the image’s need to be made and secured important?|A dependent object cannot compare with the Creator|The image is too expensive for ordinary people|Only a richer image could represent God|The craftsperson has failed to use enough gold',
  'What tension undercuts the proposed “likeness” of God in these verses?|People must construct and steady the object they would worship|The worth of an image changes with its materials|The question assumes every image depicts a nation|The worshipper must choose a tree that will endure'),
 ('40:21-26', 'The Lord stretches out the heavens and names their hosts; earthly rulers wither before Him.',
  'What does the Lord call the stars by?|Their names|Their ages|Their colors|Their sizes',
  'Why place fading rulers beside the ordered host of heaven?|To contrast temporary earthly rank with enduring divine command|To show rulers can direct the stars|To say stars are stronger than God|To identify which ruler built the heavens',
  'What answer do verses 21–26 give to the challenge “to whom will ye liken me”?|No earthly ruler or fashioned object matches the Creator who orders the heavens|The mightiest prince can approach God’s power|The host of heaven provides a literal portrait of God|The question is settled by the quality of an image’s metal'),
 ('40:27-29', 'God answers Israel’s fear of being overlooked by affirming His unfailing understanding and power to strengthen the faint.',
  'What does God give to people who feel weak?|Strength|More burdens|A carved image|A secret name',
  'How does the description of the tireless Creator answer Israel’s complaint?|God has both awareness and strength to help|God is too vast to notice one people|Israel must solve the problem without Him|Only strong people deserve His attention',
  'Why place Israel’s claim that its way is hidden immediately before God’s inexhaustible understanding?|The juxtaposition directly challenges the idea of divine neglect|It grants the complaint and changes the subject|It shows knowledge, but not power, is the issue|It restricts God’s concern to the heavens'),
 ('40:30-31', 'Even youths grow weary, but those who wait on the Lord receive renewed strength.',
  'Who receives new strength in Isaiah 40:31?|Those who wait on the Lord|Those who rely on youth|Those who finish the race first|Those who gather at the mountain',
  'Why does Isaiah mention that even young people grow tired?|To show human vigor has limits|To blame young people for weak faith|To forbid running and walking|To say strength depends on age',
  'What makes “waiting” active rather than passive in the closing image?|Trust in the Lord sustains renewed running and walking|It excuses the people from any future movement|It requires physical stillness until youth returns|It makes personal endurance independent of God'),
 ('41:1-4', 'The Lord summons the nations to judgment and identifies Himself as the one who directs generations from beginning to end.',
  'Who says He is with the first and the last?|The Lord|A goldsmith|A foreign king|A messenger from Zion',
  'What does the courtroom invitation in Isaiah 41 emphasize?|The nations must reckon with the Lord’s action in history|The nations are invited to choose a new idol|The judge needs the nations to explain creation|The first conqueror has the final word',
  'How does “calling the generations from the beginning” answer the question about the rising conqueror?|It locates historical upheaval within the Lord’s enduring agency|It identifies the conqueror as the final judge|It suggests later generations must repeat the same campaign|It treats the nations’ fear as proof of their innocence'),
])

day('2026-09-29', [
 ('41:6-7', 'The nations encourage one another while fastening an idol so it cannot move.',
  'Why do the workers fasten the image with nails?|So it will not move|So it can see|So it can speak|So it can grow',
  'What is quietly ironic about the workers’ encouragement?|Their god needs their help to stay in place|Their tools are too weak for the task|They work alone despite calling for help|They mistake the image for a living neighbor',
  'How does the cooperative making of the image answer the nations’ fear in verse 5?|They manufacture reassurance that still depends on human support|They abandon every attempt to seek security|They demonstrate that craft can control God|They fulfill the covenant promise to Abraham'),
 ('41:8-10', 'The Lord names Israel as His chosen servant and promises His presence and strength.',
  'What does the Lord tell Israel when it is afraid?|I will help you|I have forgotten you|Find another god|Hide from everyone',
  'What grounds the command “Fear thou not” in verse 10?|The Lord is with Israel and will uphold it|Israel has defeated every opponent|The future contains no hardship|Israel has made a stronger image',
  'How does calling Israel “my servant” shape the reassurance that follows?|Chosen identity is paired with divine support, not self-sufficiency|The title makes Israel equal to the Lord|The title means Israel can avoid every conflict|Chosen identity replaces the need to trust'),
 ('41:13-14', 'The Lord promises to hold Israel’s right hand even while addressing its frailty.',
  'What does the Lord say He will hold?|Israel’s right hand|A golden image|A sharp sword|A cedar branch',
  'Why pair the humbling name “worm Jacob” with “I will help thee”?|The promise rests on the Lord’s strength, not Israel’s|The name means Israel is beyond help|The Lord asks Israel to become stronger first|The image predicts that Israel will vanish',
  'What does the shift from frail “worm” to the Lord holding a hand establish?|Divine aid addresses weakness without pretending weakness is strength|The people’s weakness makes their calling invalid|The hand image transfers power to a carved idol|The Lord’s help depends on an immediate military victory'),
 ('41:15-16', 'The weak servant is pictured as an effective threshing tool and rejoices in the Lord.',
  'What does Israel do after the mountains become like chaff?|Rejoices in the Lord|Worships the mountains|Builds a new wall|Returns to its idols',
  'What does the new threshing instrument image suggest?|The Lord can make a weak servant effective|Israel must harvest grain before it can pray|Mountains are the source of Israel’s strength|The people must replace their teachers',
  'How do verses 14–16 transform the servant image?|A frail people become capable through divine action and direct praise to God|A powerful nation loses the ability to work|An idol is remade into an agricultural tool|The servant’s worth depends on natural strength'),
 ('41:17-20', 'God answers the needy with water and growth so people recognize His hand in the change.',
  'What does the Lord provide when the poor seek water?|Rivers and springs|Silver images|Stronger nails|Hidden treasure',
  'Why does the Lord turn dry places into pools?|To answer need and reveal His action|To test whether idols can swim|To keep the poor away from cities|To make every wilderness into farmland',
  'What purpose clause interprets the extravagant new landscape in verse 20?|People should recognize the Lord’s creating hand|The poor should conceal the source of water|The nations should credit Israel’s engineers|The new trees should replace the covenant people'),
 ('41:21-24', 'The Lord challenges rival gods to declare future events or act, exposing their powerlessness.',
  'What does the Lord ask the false gods to show?|What will happen|How to make a tree|Where to buy silver|Who can hammer fastest',
  'What standard does the Lord use to challenge the idols?|Show knowledge of events or power to act|Explain how their craftsmen work|Count the nations that worship them|Tell a story about a past king',
  'Why does the challenge include both prediction and the ability to do good or evil?|It tests knowledge and agency, neither of which the idols display|It grants the idols equal power over the future|It asks Israel to choose between two kinds of idols|It treats craftsmanship as proof of divinity'),
 ('41:27-29', 'The Lord provides good tidings while the idols offer no counsel and are called wind and confusion.',
  'What can the idols answer when questioned?|Nothing|Every question|Only questions about rain|Only questions about kings',
  'How is Zion’s good news contrasted with the images?|The Lord speaks while they give no counsel|The images speak more clearly than the messenger|Both offer the same warning|Zion has no message to bring',
  'What is the force of ending the courtroom scene with “wind and confusion”?|The rival claimants cannot supply the knowledge or help demanded|The Lord’s own message remains uncertain|The messenger has failed to reach Jerusalem|The nations have answered too many questions'),
 ('42:1-3', 'The Lord’s servant brings justice while treating the bruised reed and dim wick gently.',
  'What does the servant do with a bruised reed?|He does not break it|He throws it away|He uses it as a sword|He hides it from the Lord',
  'What kind of strength is shown by the servant’s care for fragile things?|Steady justice without crushing the weak|Loud power that silences everyone|Fear of taking any action|Dependence on public applause',
  'How do the quiet manner and the bruised reed refine the portrait of the servant’s mission?|Justice advances without spectacle or needless harm to the vulnerable|Justice is postponed until every weakness disappears|The servant rejects those who have already suffered|The servant’s silence signals that the mission has failed'),
 ('42:5-7', 'The Creator calls and upholds the servant to be a covenant, a light, and a liberator.',
  'Who is promised help in opening blind eyes and freeing prisoners?|The Lord’s servant|The idol maker|The frightened islands|The king of Babylon',
  'Why is the Creator introduced before the servant’s commission?|The mission rests on the life-giving God who calls and sustains|The servant must first create a new earth|The commission belongs only to those with royal power|The Creator is withdrawing from the mission',
  'How does the servant’s call extend beyond Israel in verses 6–7?|He is given as light to the Gentiles and release to captives|He replaces the Creator as a second god|He serves only those already free and seeing|He is sent to defend the existing prison system'),
 ('42:8-10', 'The Lord claims His own glory, announces new things beforehand, and calls for a new song.',
  'Why are people called to sing a new song?|The Lord announces new acts|An idol has learned to speak|The sea has become silent|A king has made a new law',
  'How do the “new things” and “new song” belong together?|New divine action calls for fresh praise|A song can make future events happen|The new song erases the Lord’s earlier works|The song is meant only for Jerusalem',
  'What links the Lord’s refusal to share glory with idols to praise from the ends of the earth?|His unique agency warrants worldwide recognition|Every nation must craft its own image of Him|The servant’s mission is limited to Israel|The new song credits the idols for coming change'),
])

day('2026-09-30', [
 ('42:11-12', 'Isaiah invites wilderness settlements, mountains, and islands to praise the Lord.',
  'Where does Isaiah call people to praise the Lord?|Across wilderness and islands|Only inside Jerusalem|Only beside the sea|Only in the temple',
  'What is the effect of naming distant places in the call to praise?|The Lord’s glory is proclaimed beyond one city|The message excludes people in cities|The wilderness is the only holy place|The islands are warned to stay silent',
  'How does the geographical spread of praise continue the “new song” of verse 10?|The response to the Lord’s action expands toward the world’s edges|The praise retreats from the nations to one sanctuary|The named places mark the limits of the servant’s work|The landscape replaces human witnesses'),
 ('42:13-16', 'The Lord moves from long silence to action and promises to guide the blind through unknown paths.',
  'What does the Lord promise to make light for the blind?|Darkness|A carved image|A dry river|A prison door',
  'How does the promise to guide the blind qualify the fierce imagery just before it?|The Lord’s action includes guidance and rescue|The Lord’s anger is aimed at every blind person|The blind must find the path without help|The guidance comes from the idols',
  'What tension does the passage hold between the warrior cry and the guiding hand?|Divine intervention judges enemies while refusing to abandon the vulnerable|The Lord first guides the nations, then forgets Israel|The warrior image cancels the promise of guidance|Both images describe the same human army'),
 ('42:18-20', 'Isaiah challenges people who have eyes and ears yet fail to observe or hear.',
  'What is wrong with the people who have eyes and ears?|They do not truly notice or listen|They cannot see any light|They have no teachers|They cannot speak to one another',
  'What distinction is Isaiah making with seeing but not observing?|Receiving signs is different from attending to them|Physical sight is a guarantee of understanding|The people have been given no message|Hearing matters only when sight fails',
  'Why does the passage call the Lord’s own servant blind?|Covenant status does not prevent failure to perceive and obey|The servant’s eyes were removed as a punishment|The title “servant” now refers only to foreign idols|Blindness is praised as the ideal way to learn'),
 ('42:21-25', 'The people’s captivity is connected to refusing the Lord’s ways, yet they fail to take the warning to heart.',
  'Why had Israel become prey to robbers in this passage?|They would not walk in the Lord’s ways|They had too few walls|They had traveled too far|They could not hear a trumpet',
  'What makes the description of burning especially troubling?|The people suffered yet still did not take it to heart|The fire was treated as an ordinary household flame|The captors offered to restore them|The people asked for help from the wrong ruler',
  'How do the question “Who will give ear?” and the unheeded fire interpret the disaster?|The crisis is also a failure to learn from covenant correction|The disaster proves the Lord had no role in history|The fire is only a weather report|The people have already responded fully to the warning'),
 ('43:1-2', 'The Redeemer calls Israel by name and promises His presence through waters and fire.',
  'What does the Lord promise in deep water and fire?|I will be with you|You will find a safer route|They will become a road|They will hide you from enemies',
  'What is the comfort in “I have called thee by thy name”?|The people are personally known and claimed by their Redeemer|Only named leaders may cross the waters|The people must earn a new name|The Lord has forgotten their earlier covenant',
  'How do “Fear not” and the water and fire images fit together?|Redemption promises presence through danger, not the absence of danger|The images show that danger was only imagined|The command asks Israel to cross without divine aid|The promise concerns water but leaves fire unanswered'),
 ('43:5-7', 'The Lord promises to gather His people from every direction because they belong to Him.',
  'From where will the Lord gather His people?|From every direction|Only from the east|Only from the temple|Only from the desert',
  'What does the four-direction gathering show about the promise?|Distance will not prevent the Lord’s claim on His people|Only people near Jerusalem can return|The Lord chooses one direction as holy|The gathering is limited to soldiers',
  'How do the directional commands serve the statement “Fear not: for I am with thee”?|They turn personal reassurance into a comprehensive gathering promise|They replace reassurance with a map of conquest|They say the people must gather themselves without God|They confine God’s presence to the east'),
 ('43:8-12', 'Israel is called to witness that the Lord declared and saved, unlike rival gods.',
  'What are the people called to be for the Lord?|Witnesses|Carpenters|Prison guards|Rival gods',
  'What should Israel’s witness establish in the gathering of nations?|The Lord declared and saved; He alone is God|Israel’s own strength secured its rescue|The nations missed an earlier warning|A human king planned the rescue',
  'How does the witness scene answer the blindness language of verse 8?|Those summoned to perceive can testify from the Lord’s saving acts|Blindness disqualifies Israel from every future role|The court asks Israel to praise foreign gods|The witness is a craftsman defending his image'),
 ('43:14-17', 'The Lord identifies Himself as Israel’s redeemer and recalls a way through the sea that overcame armed power.',
  'What path does the Lord say He made?|A path through the sea|A tunnel through a mountain|A bridge over Babylon|A road around the desert',
  'Why recall the sea path while promising action against Babylon?|A past deliverance supports trust in a new one|Babylon had already built the sea path|The people must repeat every detail of the earlier journey|The sea is safer than every desert',
  'How does the recollection of defeated chariots function in the announcement about Babylon?|It presents the Lord’s earlier mastery over empire as grounds for future hope|It claims Babylon and Egypt were the same army|It shifts responsibility for redemption to Israel’s weapons|It implies the coming action can only occur at sea'),
 ('43:18-20', 'The Lord announces a new thing: a way in the wilderness and water in the desert.',
  'What new thing will the Lord provide in the desert?|A way and water|A stronger idol|A higher throne|A deeper prison',
  'Why does Isaiah say not to dwell on former things just after recalling the sea?|The people should recognize a fresh act of deliverance|The old deliverance was a mistake|The Lord has stopped guiding His people|The coming act has no relation to the past',
  'What is the relationship between the sea path and the new desert rivers?|The earlier rescue is a pattern, while the promised rescue exceeds mere repetition|The former rescue is denied so the new one can be believed|Both descriptions concern the same location and moment|The new rivers show that the sea path was unnecessary'),
 ('43:19-20', 'The new water is given in the wilderness so the Lord’s chosen people can drink.',
  'Why does water flow in the wilderness?|To give the Lord’s people drink|To flood the cities|To power a mill|To hide a treasure',
  'How does the response of wild creatures deepen the picture of renewal?|Even the nonhuman world honors the giver of water|Only wild creatures receive the water|The people become less important than the animals|The creatures create the rivers themselves',
  'Why include animals honoring God beside the people’s need for water?|The provision is both practical rescue and a sign of divine glory in creation|The animals are the only true witnesses of redemption|The water exists mainly to remove the animals from the desert|The image narrows the promised change to a single spring'),
])

day('2026-10-01', [
 ('43:21-25', 'Though Israel has wearied the Lord with sins, He promises to blot out transgressions for His own sake.',
  'What does the Lord promise to do with His people’s sins?|Blot them out|Write them on stone|Give them to Babylon|Hide them in a box',
  'What contrast gives the forgiveness promise its force?|The people failed to honor God, yet He offers to erase their sins|The people brought many offerings, so God owes them pardon|God forgets the people while remembering their sins|The people’s sacrifices replaced the need for repentance',
  'Why is “for mine own sake” significant after the catalogue of failed devotion?|Pardon rests on God’s gracious purpose rather than Israel’s performance|It means God has no concern for the covenant people|It credits Israel’s offerings with earning redemption|It makes forgiveness independent of any divine promise'),
 ('44:1-4', 'The Lord promises Spirit and blessing to descendants, pictured as water on thirsty ground and willows by streams.',
  'What does the Lord promise to pour on His people’s children?|His Spirit and blessing|Molten silver|Dust from Babylon|Ashes from idols',
  'How does the water image explain the promise to descendants?|God’s Spirit brings growth where life was dry|The descendants must build irrigation canals first|The promise concerns only physical rain|The children will no longer need guidance',
  'How does the movement from dry ground to willows interpret the Spirit promise?|Divine blessing changes a vulnerable future into flourishing life|The metaphor restricts the promise to farming families|The children become independent of the Lord once grown|The plants represent the idols Israel must make'),
 ('44:5', 'The renewed people openly identify themselves with the Lord and with Israel.',
  'What does one person say about belonging to God?|I am the Lord’s|I belong to Babylon|I made the Lord|I have no name',
  'What does the repeated naming in verse 5 show?|People willingly claim covenant belonging|Each person is choosing a different god|Names have replaced the need for faith|Israel’s identity is being erased',
  'How does verse 5 answer the previous promise of Spirit on descendants?|Renewed identity is publicly embraced by those who receive the blessing|The descendants reject every connection to Jacob|The blessing produces secrecy rather than allegiance|The names are imposed by foreign rulers'),
 ('44:6-8', 'The Lord calls Himself first and last, denies any rival God, and names His people as witnesses.',
  'What does the Lord say about other gods beside Him?|There is no other God|They are all stronger|They will soon help Israel|They made the earth',
  'Why are the people called witnesses after the Lord says He is first and last?|They can testify to His unique, enduring acts|They must prove their own power to foretell events|They are asked to design a better image|They must choose which god created them',
  'How does the “first and last” claim frame the challenge to rival gods?|The Lord’s comprehensive agency leaves no comparable divine power|It divides history between two equal gods|It restricts divine knowledge to the distant past|It transfers responsibility for the future to witnesses'),
 ('44:9-11', 'The makers and devotees of images are themselves limited people; the images cannot profit them.',
  'Can the carved image help the people who make it?|No, it cannot profit them|Yes, it can create them|Yes, it can forgive them|Yes, it can guide every nation',
  'Why does Isaiah draw attention to the image makers being human?|Their product cannot outrank the makers who depend on God|Human skill is forbidden in every setting|The workers are more powerful than God|The image is valuable only before it is finished',
  'What is the argument in calling the image’s makers its witnesses?|Those who know its human origin expose its inability to save|The makers can certify its divine origin|The makers replace Israel as the Lord’s witnesses|The image has no need for any witness'),
 ('44:12-13', 'The smith tires and thirsts while the carpenter measures an image shaped like a human.',
  'What happens to the smith as he works?|He becomes tired and thirsty|He creates rain|He stops needing food|He turns into an image',
  'What does the tired smith reveal about the idol-making process?|It depends on a limited worker|It gives the worker lasting strength|It produces a living helper|It proves the image can create life',
  'How do the smith’s fatigue and the carpenter’s measurements sharpen Isaiah’s critique?|The supposed god is fashioned through ordinary, dependent human labor|The workers are punished for poor craftsmanship|The measurements reveal a divine blueprint|The fatigue shows the image is already powerful'),
 ('44:14-17', 'The same wood warms a person, cooks food, and becomes an object of worship.',
  'What else does the person do with the wood used for an idol?|Burns some to cook food|Plants it in the sea|Builds a prison from it|Uses it to make rain',
  'What makes worshipping the leftover wood absurd in Isaiah’s example?|The same material was ordinary fuel minutes earlier|The wood is too expensive for worship|The idol has moved from its place|The food was cooked without a fire',
  'What logical contradiction does the split log expose?|A person treats one part as fuel and the remainder as a savior|A person uses one tree for two crafts|Wood can be both strong and flammable|The worker needs both heat and food'),
 ('44:18-20', 'The idol maker fails to consider the contradiction and is described as feeding on ashes.',
  'What question does the idol maker fail to ask?|Am I trusting a piece of wood?|Will my food be ready?|Where should I plant a tree?|Who sharpened my axe?',
  'What is the force of “he feedeth on ashes”?|His chosen trust cannot nourish or deliver him|He has no ordinary food available|The idol has fed him a meal|He is punished for cooking bread',
  'Why does Isaiah emphasize a failure to reflect, not merely a mistaken craft technique?|The deeper problem is a deceived judgment that cannot name its own lie|A better-shaped image would solve the problem|Only the choice of tree was mistaken|The passage praises the worker’s practical reasoning'),
 ('44:21-23', 'The Lord tells Israel it is not forgotten and has been redeemed, so it should return and sing.',
  'What does the Lord tell Israel after describing the idols?|You are not forgotten|You must make a new image|You are beyond return|You should trust the smith',
  'How does “return unto me; for I have redeemed thee” differ from the idol maker’s prayer?|The Lord initiates rescue and invites response|The people must first carry God to safety|The image offers forgiveness before it is made|The return depends on the quality of a crafted object',
  'What is the causal order in the invitation to return and the call to cosmic praise?|God’s redeeming act grounds both Israel’s return and creation’s song|Israel’s song purchases redemption|The mountains forgive Israel before the Lord acts|The idol maker’s insight produces the praise'),
 ('44:24-27', 'The Creator promises to rebuild Jerusalem and confirms His messengers’ word.',
  'What does the Lord say will happen to Jerusalem?|It will be inhabited again|It will become an idol|It will sink into the sea|It will remain empty forever',
  'Why are creation and Jerusalem’s rebuilding mentioned together?|The One who made all things can accomplish restoration|Rebuilding a city is identical to creating the heavens|The city must be rebuilt before God can act|Human builders are more reliable than prophets',
  'How does the Creator’s self-description support the promise about ruined cities?|His independent creative power underwrites His word of restoration|It implies He needs diviners to predict the work|It makes the city’s future depend on idol makers|It means only the heavens, not the city, matter'),
])

day('2026-10-02', [
 ('44:28-45:4', 'The Lord names Cyrus as an instrument for rebuilding Jerusalem and releasing captives, though Cyrus has not known Him.',
  'What does the Lord say Cyrus will help rebuild?|Jerusalem and its temple|Babylon’s idols|A wall around Egypt|A new sea road',
  'What is surprising about Cyrus being called by name?|The Lord uses him even though he has not known the Lord|Cyrus is one of Isaiah’s sons|Cyrus asks to become a prophet|Cyrus has already rebuilt every city',
  'How does “though thou hast not known me” qualify the title given to Cyrus?|Divine appointment does not imply Cyrus personally understood the Lord|Cyrus’s mission depended on recognizing every prophecy|The title makes Cyrus a second covenant God|The Lord’s plan was discovered by Cyrus first'),
 ('45:4-6', 'The Lord calls Cyrus for Israel’s sake so people across the earth may know that He alone is God.',
  'For whose sake does the Lord say He called Cyrus?|Jacob and Israel|The image makers|Only Cyrus’s family|Babylon’s astrologers',
  'What wider purpose accompanies the Lord’s action for Israel?|People from east to west may know He alone is God|Cyrus may be worshipped in every nation|Israel may hide its identity|Each region may choose a separate creator',
  'How do the particular and universal aims fit together in verses 4–6?|Calling Cyrus for Israel also discloses the Lord’s uniqueness worldwide|Helping Israel prevents other peoples from knowing God|The worldwide claim makes Israel irrelevant|Cyrus is selected only to teach geography'),
 ('45:7-8', 'The Lord claims authority over light, darkness, peace, and calamity, then calls for righteousness and salvation.',
  'What does the Lord invite to spring up together?|Righteousness and salvation|Gold and silver|Horses and chariots|Prisons and chains',
  'What does the range from light to darkness stress?|The Lord governs both ease and hardship|The Lord is unable to bring peace|Darkness belongs to a rival god|The people must worship the sky',
  'How should the paired claims about opposite conditions be read beside the call for salvation?|The Lord governs the whole historical scene while directing it toward righteousness|The opposites establish two equal divine powers|The passage says calamity itself is the final good|The call for salvation narrows God’s authority to weather'),
 ('45:9-12', 'The clay-and-maker image warns against treating the Creator as if the created thing controlled Him.',
  'What does Isaiah compare a person arguing with the Maker to?|Clay arguing with its potter|A sheep following its shepherd|A child learning from a teacher|A traveler finding a road',
  'What is the point of the clay’s question to its maker?|A creature lacks the maker’s perspective and authority|A potter cannot choose a design|Clay has better plans than a potter|All questions are forbidden',
  'How does the potter image support the following creation claim?|The Maker’s authority precedes the creature’s judgment of His work|The earth is literally a clay vessel|The people’s objections prove the Maker has no purpose|Cyrus becomes the potter who created the heavens'),
 ('45:13', 'The one raised up will rebuild the city and release captives without demanding a price.',
  'What happens to the captives in the Lord’s plan?|They are set free|They are sold for gold|They build new prisons|They remain in Babylon',
  'Why does “not for price nor reward” matter to the release promise?|Deliverance is not presented as a transaction for payment|The captives must pay after returning|The city cannot be rebuilt with money|Only wealthy people will be freed',
  'How does the unpriced release connect Cyrus’s role to the Lord’s purpose?|The ruler’s action serves divine restoration rather than private profit|The Lord sells the captives to a kinder ruler|The city is rebuilt only after tribute is collected|Cyrus is promised the temple as a personal prize'),
 ('45:15-17', 'Idol makers are shamed, while Israel is promised enduring salvation in the Lord.',
  'Who is promised lasting salvation?|Israel in the Lord|The carved images|The image makers as makers|The gates of brass',
  'What contrast organizes these verses?|Shame for idol makers and lasting salvation for Israel|Shame for Israel and triumph for idols|Equal salvation through every image|Equal failure for the Lord and the idols',
  'How does “everlasting salvation” answer the temporary prestige of idols?|The Lord’s rescue outlasts the false objects and their makers|An image becomes everlasting once made of gold|The promise depends on hiding God forever|The makers’ shame is itself Israel’s salvation'),
 ('45:18-19', 'The Creator formed the earth to be inhabited and says He did not tell Jacob to seek Him in vain.',
  'Why did God form the earth in this passage?|To be inhabited|To remain empty|To house only idols|To hide His voice',
  'How do creation’s purpose and the call to seek God reinforce each other?|God’s work and words have a meaningful end|God made an empty earth but changed His mind|Seeking God is meant to fail|Creation is unrelated to the people’s hope',
  'What argument against futility links “not in vain” to “Seek ye me”?|The purposeful Creator has not issued an empty invitation|The world’s purpose can be found only by Cyrus|The Lord’s speech is deliberately secret|The invitation is limited to those who already know the answer'),
 ('45:20-22', 'The Lord contrasts images that cannot save with His invitation to all the ends of the earth to look to Him and be saved.',
  'Who is invited to look to the Lord and be saved?|All the ends of the earth|Only the idol makers|Only Jerusalem’s rulers|Only people already free',
  'What makes the invitation wider than Israel’s earlier promise?|It is addressed to all the earth|It is given only to Cyrus|It excludes those who made idols|It is limited to Jerusalem’s walls',
  'How does the image that “cannot save” sharpen the open invitation in verse 22?|A powerless alternative is set against salvation offered by the one God to all|The image must first teach the nations to look|The invitation asks nations to carry their idols to Jerusalem|Salvation depends on which wooden image is chosen'),
 ('45:23-25', 'The Lord declares universal acknowledgment of Him and says righteousness and strength are in Him.',
  'Where does Isaiah say strength is found?|In the Lord|In a goldsmith|In a gate of brass|In an idol’s wood',
  'What does every knee bowing signify in the passage?|Recognition of the Lord’s rightful authority|The end of all human movement|Cyrus becoming the only king|The idols gaining equal honor',
  'How does universal acknowledgment relate to Israel’s being justified in the Lord?|Both rest on the Lord as the source of righteousness and strength|Only Israel bows while the nations remain outside|Acknowledgment transfers the Lord’s power to idols|Israel becomes righteous by its own military success'),
 ('46:1-8', 'The idols must be carried by animals, while the Lord promises to carry and deliver His people through old age.',
  'Who carries whom in the Lord’s promise?|The Lord carries His people|The idols carry their makers|The animals carry the Lord|Cyrus carries every idol',
  'What is the key contrast between the idols and the Lord?|People carry idols; the Lord carries people|Both must be carried by animals|The idols answer while the Lord is silent|The Lord remains fixed while idols travel',
  'Why is the repeated “carry” language central to the argument?|Idols burden carriers; the Lord bears His people|Both sides rely equally on human shoulders|The animals become the true redeemers|The passage concerns the cost of moving statues'),
])

day('2026-10-03', [
 ('46:9-10', 'The Lord alone declares the end from the beginning, and His counsel stands.',
  'What does the Lord say will stand?|His counsel|Babylon’s throne|A carved image|The astrologers’ charts',
  'Why does remembering former things support trust in the future?|The Lord’s past acts support His claim that His purpose stands|The past proves that no new thing can happen|Remembering replaces every need to act|The old things were controlled by Babylon',
  'How does foretelling the end relate to the claim “none like me”?|The Lord’s enduring purpose and knowledge distinguish Him from rival claimants|The Lord depends on a rival to explain the future|The claim means future events are beyond divine action|Remembering the past makes the future irrelevant'),
 ('46:11-13', 'The Lord calls an agent from afar and promises to bring salvation near despite the hearers’ stubbornness.',
  'What does the Lord promise to bring near?|His salvation|A wooden idol|Babylon’s throne|A new prison',
  'What is the point of “I have spoken it, I will also bring it to pass”?|The Lord’s purpose becomes action|The Lord needs Babylon to approve His words|The speaker has forgotten what He said|The agent can overturn the Lord’s plan',
  'How do distant agent and near salvation work together?|God can use far-off action to make His promised rescue immediate|Distance keeps the agent outside the Lord’s purpose|The people must travel far before God can speak|Salvation draws near through Israel’s own resolve'),
 ('47:1-5', 'Babylon is called down from her throne to the dust and loses the title “lady of kingdoms.”',
  'What happens to Babylon’s throne in Isaiah 47?|She loses it|It becomes higher|It turns to gold|It is moved to Zion',
  'What does the command to sit in dust convey about Babylon?|Her status and power are being brought low|She is preparing a festival|She is resting after victory|She is hiding a royal treasure',
  'How does the address to “daughter of Babylon” intensify the descent from throne to dust?|A once-cherished imperial identity is stripped of prestige|Babylon is promoted to a higher title|The image concerns only a literal royal daughter|The humiliation is unrelated to political power'),
 ('47:6-7', 'Babylon showed no mercy to the Lord’s people and acted as though its rule would last forever.',
  'How did Babylon treat the people placed in its hand?|Without mercy|With gentle care|As honored guests|As free rulers',
  'Why does Babylon’s claim of permanent rule draw judgment?|It ignored both cruelty and the possibility of an end|It offered mercy too quickly|It refused to build a larger capital|It listened too closely to Israel’s warnings',
  'How do lack of mercy and failure to consider “the latter end” reinforce each other?|Arrogance let Babylon abuse temporary power as if it were permanent|Mercy made Babylon forget its own strength|A permanent empire would have justified the abuse|The passage criticizes only Babylon’s planning skills'),
 ('47:10-11', 'Babylon’s hidden wickedness and reliance on its own wisdom cannot prevent sudden disaster.',
  'What does Babylon wrongly say about its wrongdoing?|No one sees me|I need forgiveness|I will restore the captives|I have listened to Isaiah',
  'Why does the warning pair secret wickedness with trusted wisdom?|Neither concealment nor cleverness can prevent judgment|The two together guarantee safety|Wisdom has already led Babylon to repent|Only visible wrongs can have consequences',
  'How does Babylon’s “none seeth me” echo its “none else beside me”?|Both make the self the measure of reality and obscure accountability|One is a confession and the other a prayer|Both acknowledge the Lord’s complete knowledge|They show Babylon had abandoned confidence in its power'),
 ('47:12-15', 'Astrologers and other advisers cannot save Babylon; they scatter as its judgment arrives.',
  'Can Babylon’s stargazers save it?|No|Yes, by reading the stars|Yes, by buying gold|Yes, by building an idol',
  'What is Isaiah testing when he tells Babylon to stand with its enchantments?|Whether its trusted practices can actually deliver it|Whether its scholars can name more stars|Whether it can make a warmer fire|Whether merchants can travel faster',
  'Why end with advisers wandering away rather than rescuing Babylon?|The supports on which Babylon relied prove powerless under judgment|The advisers have successfully carried out their plan|The merchants become new rulers of Zion|The fire is meant chiefly to warm the astrologers'),
 ('48:1-5', 'Israel invokes the Lord’s name without truth, and the Lord announced events beforehand so idols could not receive credit.',
  'Why did the Lord announce things before they happened?|So idols could not claim the credit|So Israel could avoid listening|So Babylon could build an image|So people could forget the events',
  'What mismatch does the opening of Isaiah 48 expose?|Israel names the Lord while failing to live truthfully|Israel uses the wrong title for the Lord|Israel hears a prophetic word but doubts its timing|Israel trusts its ancestry more than its city',
  'How do Israel’s false profession and the Lord’s advance announcement fit one argument?|The Lord denies both ritual pretense and the transfer of His acts to idols|The Lord approves profession regardless of conduct|The announcement proves the idols are His partners|Israel’s obstinacy makes divine disclosure unnecessary'),
 ('48:6-8', 'The Lord reveals new things so Israel cannot claim it already knew them, despite its closed ears.',
  'Why does the Lord tell Israel new things?|So they can recognize His work|So they can praise an idol|So they can hide the past|So they can stop listening',
  'What does “Behold, I knew them” wrongly claim in this passage?|That Israel already possessed the Lord’s new disclosure|That Israel deserved the Lord’s favor|That Babylon could not be judged|That the message concerned earlier generations',
  'How does the disclosure of new things answer Israel’s stubbornness?|It removes a possible claim of prior knowledge while exposing refusal to hear|It rewards obstinacy with control over future events|It invites Israel to treat the disclosure as a familiar story|It makes the new things creations of Israel’s idols'),
 ('48:9-11', 'The Lord delays anger and refines Israel in affliction for His name’s sake.',
  'What image describes Israel’s hardship?|A furnace of affliction|A road of flowers|A gold throne|A river of peace',
  'Why does the Lord say He delays anger?|To preserve His purpose and name while refining His people|Because the disaster was less serious than it seemed|Because Israel has already completed its return|To give the idols time to save Israel',
  'How does refinement differ from destruction in the Lord’s explanation?|Affliction is framed as a preserving work tied to His name|The furnace proves that the covenant is canceled|Refinement earns glory for the idols|The process removes the need for any divine patience'),
 ('48:12-14', 'The Lord calls Himself first and last, creator of earth and heavens, and summons people to hear His purpose for Babylon.',
  'Who laid the foundation of the earth in this passage?|The Lord|Babylon|An astrologer|A carved image',
  'Why repeat the Lord’s creator identity before speaking of Babylon?|His command over creation grounds trust in His historical purpose|Babylon must create the heavens before it can be judged|The Lord no longer speaks to Israel|The stars determine the Lord’s next act',
  'How do creation and the summons to assemble support the claim about Babylon?|The sovereign Creator calls witnesses to hear a purpose He can accomplish|The summons delegates control of Babylon to the stars|The creation claim limits the Lord to distant events|The Lord needs the assembly to decide His plan'),
])

day('2026-10-04', [
 ('48:17-18', 'The Lord teaches the way to go and says obedience would have made Israel’s peace like a river.',
  'What is peace compared to when people heed the Lord?|A river|A fortress|A sword|A cloud of dust',
  'How are divine teaching and the river image connected?|Following the Lord’s direction is linked with abundant peace|Peace comes from learning the route without following it|The river replaces the need to choose a way|Travelers need to find a river before they obey',
  'What force does the lament “O that thou hadst hearkened” add to the river image?|It presents lost peace as the consequence of refusing available guidance|It suggests the offered peace belonged to earlier generations|It treats obedience as a way to control the Lord|It limits the promise to a future harvest'),
 ('48:20-21', 'Israel is told to leave Babylon and announce redemption; the Lord provided water in the desert.',
  'What are the people told to do when leaving Babylon?|Announce that the Lord redeemed them|Carry Babylon’s idols home|Stay silent about their journey|Build a new prison',
  'Why recall water from the rock after calling people out of Babylon?|It connects the new departure to the Lord’s proven provision|It instructs them to carry a rock for water|It credits Babylon with sustaining the desert journey|It says the desert has no real danger',
  'How do flight from Babylon, public proclamation, and desert water form one picture?|Redemption is an exodus to be announced and sustained by God|The people must escape without divine help or witness|The water story replaces the need to leave Babylon|The proclamation is meant only for those still captive'),
 ('49:1-3', 'The servant is called from the womb and described with sword and arrow imagery.',
  'When does the servant say the Lord called him?|From the womb|After becoming a king|After leaving Babylon|When he made an idol',
  'What do the sharp sword and polished arrow images suggest?|The servant is prepared for a purposeful mission|The servant is told to build weapons for himself|The servant’s only task is military conquest|The servant must remain hidden forever',
  'How do being named from the womb and hidden like an arrow fit together?|The mission is appointed early and prepared before its public work|The servant chooses the mission only after a failed battle|The arrow image denies any divine calling|The servant is hidden because God has forgotten him'),
 ('49:4-5', 'The servant feels his labor has been in vain but entrusts its judgment to the Lord, who remains his strength.',
  'How does the servant feel about his hard work?|It seems wasted|It has made him rich|It has ended every problem|It has freed every prisoner',
  'What does the servant do despite feeling that his work was wasted?|He entrusts the outcome to the Lord|He waits for a ruler to judge it|He asks his audience to praise it|He measures its success by applause',
  'How does the servant’s complaint coexist with his confidence?|He names apparent failure while locating vindication and strength with God|He denies that the work was difficult|He assumes success can only be measured immediately|He concludes the Lord has withdrawn the call'),
 ('49:6', 'The servant’s work extends from restoring Israel to being a light to the Gentiles and salvation to earth’s end.',
  'Who else receives light through the servant besides Israel?|The Gentiles|Only Babylon’s king|Only temple workers|Only the servant’s family',
  'What does “It is a light thing” mean here?|Restoring Israel alone is too narrow for the servant’s mission|Restoring Israel is too easy to matter|The servant’s mission is being canceled|The Gentiles must replace Israel',
  'How does the second commission enlarge the first without discarding it?|Israel’s restoration remains, while salvation is extended to the nations|The nations are included only after Israel is rejected|The servant must choose one audience and abandon the other|The first task was a mistaken prophecy'),
 ('49:7-9', 'The despised servant is chosen and preserved; he will help establish inheritance and call prisoners into freedom.',
  'What message does the servant bring to prisoners?|Go forth|Stay hidden|Make a throne|Carry an idol',
  'What contrast marks the servant’s standing in verse 7?|Despised by people but chosen by the faithful Lord|Praised by rulers but rejected by God|Known among nations but forgotten by Israel|Powerful only while serving Babylon',
  'How do public contempt and the Lord’s promise to preserve the servant interact?|Human rejection does not nullify the servant’s covenant mission|Contempt proves the Lord chose the wrong servant|Preservation means the servant will avoid every hardship|The covenant depends on immediate royal approval'),
 ('49:9-13', 'The freed are guided to food and water, and heaven and earth are called to rejoice at the Lord’s comfort.',
  'What does the Lord promise the freed travelers?|Guidance to food and water|A new prison|A longer exile|An image to carry',
  'Why do mountains and earth break into song after the travel promises?|Creation celebrates the Lord’s mercy to afflicted people|The journey is valuable only for its scenery|The travelers have built a new kingdom|The captives are expected to entertain the nations',
  'How do pasture, springs, and a raised highway develop the release of prisoners?|Freedom includes sustained care and a passable return, not merely opened doors|The images replace the earlier call to leave captivity|The travelers are told to find their own water|The highway is intended for Babylon’s army'),
 ('49:14-16', 'Zion says the Lord has forgotten her; He answers with the image of a mother and engraved palms.',
  'What does the Lord say when Zion thinks He forgot her?|I will not forget you|I have chosen another city|I cannot hear you|You must make an image',
  'Why does the Lord use a mother’s care to answer Zion?|To show His remembrance is deeply personal and enduring|To make His memory depend on human parents|To ask Zion to forget its children|To change the subject from Zion’s loss',
  'How do the mother comparison and engraved palms answer Zion’s exact complaint?|Both insist Zion remains continually present to the Lord|Both promise an immediate end to the city’s hardship|Both shift responsibility for remembrance to Zion alone|Both identify the cause of exile as forgotten names'),
 ('49:18-23', 'Zion’s returning children will fill formerly desolate places, and nations will help bring them home.',
  'What happens to Zion’s once-empty places?|They fill with returning children|They become idol workshops|They stay empty forever|They turn into rivers',
  'Why does Zion wonder where the children came from?|The return is greater than her expectation after loss|She expected the return to follow another route|The children belong only to Babylon|The city mistakes the return for an earlier gathering',
  'How does the crowding of formerly desolate places reverse Zion’s earlier fear?|The apparent abandonment gives way to a surprising abundance of children|The desolation proves the children cannot return|The nations keep the children for themselves|The restoration is limited to rebuilding walls'),
 ('49:24-26', 'The Lord promises to rescue even captives held by the mighty and to contend with their oppressors.',
  'Who will save the children from powerful captors?|The Lord|The captors themselves|A carved image|The desert animals',
  'What is the answer to the question about freeing the mighty one’s captive?|The Lord will contend with the captor and deliver them|The captives must accept permanent defeat|Only a stronger idol can bargain for them|The question has no answer in the passage',
  'How does the final rescue promise answer Zion’s doubt about losing her children?|The Lord claims power even over apparently secure captors|Zion must first become stronger than every empire|The children’s return depends on their captors’ kindness|The Lord admits the captivity is beyond Him'),
])

def build():
    for date, rows in BANK.items():
        levels = {key: [] for key in ('kid', 'high-school', 'expert')}
        for number, (reference, explanation, *versions) in enumerate(rows, 1):
            for offset, (level, version) in enumerate(zip(levels, versions)):
                parts = version.split('|')
                assert len(parts) == 5, (date, number, level)
                shift = (number + offset) % 4
                choices = parts[2:]
                choices.insert(shift, parts[1])
                options = [{'id': chr(97 + i), 'text': value} for i, value in enumerate(choices)]
                chapter, verse = reference.split(':', 1)
                start = verse.split('-')[0]
                url = f'https://www.churchofjesuschrist.org/study/scriptures/ot/isa/{chapter}.{start}?lang=eng'
                levels[level].append({
                    'id': f'{date}-{level}-{number:02d}', 'date': date, 'difficulty': level,
                    'question': parts[0], 'options': options,
                    'correctOptionId': chr(97 + shift), 'explanation': explanation,
                    'source': {'reference': f'Isaiah {reference}', 'url': url},
                })
        doc = {'date': date, 'levels': levels}
        doc['quizDuel'] = build_exports(doc)
        (ROOT / f'{date}.json').write_text(json.dumps(doc, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

if __name__ == '__main__':
    build()
