from __future__ import annotations


def q(objective, stem, correct, distractors, explanation):
    return {
        "objective": objective,
        "stem": stem,
        "options": [correct, *distractors],
        "answer": "A",
        "explanation": explanation,
    }


VIDEO_QUESTIONS = {
    "03.01": [
        q(
            "Identify the source of MRI signal.",
            "Which property makes hydrogen especially useful for clinical MRI?",
            "It is abundant in the body and has a nonzero nuclear spin",
            [
                "It is the only element that can absorb radiofrequency energy",
                "Its nucleus contains no electrically charged particles",
                "It produces ionizing radiation when placed in a magnetic field",
            ],
            "Hydrogen is plentiful in water and fat, and its single proton has spin and a magnetic moment. MRI detects radiofrequency signals from those protons rather than ionizing radiation.",
        ),
        q(
            "Explain net longitudinal magnetization.",
            "Why does tissue develop a small net magnetization parallel to the main magnetic field?",
            "Slightly more protons occupy the lower-energy parallel state",
            [
                "All protons align parallel and stop precessing",
                "Equal parallel and antiparallel populations rotate in phase",
                "The gradient coils force antiparallel protons out of the tissue",
            ],
            "The parallel state is slightly lower in energy, so it contains a small population excess at thermal equilibrium. Most individual magnetic moments cancel, but that excess produces net longitudinal magnetization.",
        ),
        q(
            "Relate field strength to precession.",
            "What happens to the Larmor frequency when the main magnetic field strength increases?",
            "It increases in direct proportion to field strength",
            [
                "It decreases in inverse proportion to field strength",
                "It remains fixed for a given tissue",
                "It changes only when a gradient is applied",
            ],
            "For a given nucleus, the Larmor frequency equals the gyromagnetic ratio multiplied by magnetic field strength. A stronger B0 therefore makes hydrogen spins precess faster.",
        ),
        q(
            "Describe resonance and excitation.",
            "Which radiofrequency pulse most efficiently transfers energy to hydrogen protons?",
            "A pulse applied perpendicular to B0 at the hydrogen Larmor frequency",
            [
                "A pulse applied parallel to B0 at any frequency",
                "A static pulse matched to the gradient switching frequency",
                "A pulse perpendicular to B0 at half the Larmor frequency",
            ],
            "Resonance occurs when the applied RF field matches the spins' Larmor frequency. The transverse B1 field then tips the net magnetization and creates phase coherence.",
        ),
        q(
            "Explain signal reception.",
            "What directly induces voltage in an MRI receiver coil after excitation?",
            "Changing transverse magnetization rotating near the coil",
            [
                "Static longitudinal magnetization aligned with B0",
                "The permanent magnetic field of stationary tissue",
                "X-rays emitted as excited protons return to equilibrium",
            ],
            "Precessing transverse magnetization creates a changing magnetic flux through the receiver coil, inducing voltage by Faraday's law. Static longitudinal magnetization does not by itself generate the measured time-varying signal.",
        ),
    ],
    "03.02": [
        q(
            "Distinguish MRI coil functions.",
            "Which component primarily creates the strong, uniform B0 field in a clinical MRI scanner?",
            "The superconducting main magnet",
            [
                "The radiofrequency receiver coil",
                "The three orthogonal gradient coils",
                "The shim-independent surface coil",
            ],
            "The superconducting main magnet produces the static B0 field, conventionally directed along the bore's longitudinal axis. Gradient and RF coils modify or interact with that field for localization and signal generation.",
        ),
        q(
            "Identify gradient coil roles.",
            "What is the principal function of the x, y, and z gradient coils?",
            "To impose controlled spatial variations on the main magnetic field",
            [
                "To maintain superconductivity by cooling the magnet",
                "To amplify the voltage detected by the receiver",
                "To eliminate all tissue-dependent relaxation differences",
            ],
            "Gradient coils add small, linearly varying magnetic fields along three spatial axes. Those variations change Larmor frequency or phase by position and make spatial encoding possible.",
        ),
        q(
            "Identify RF transmit function.",
            "What does the transmit RF coil produce during excitation?",
            "A B1 magnetic field oscillating near the Larmor frequency",
            [
                "A permanent increase in the static B0 field",
                "A linear magnetic field that selects image rows",
                "A direct electric current inside the patient's tissues",
            ],
            "The transmit coil generates the oscillating B1 field used to tip magnetization through resonance. It does not replace the main field or the spatial gradients.",
        ),
        q(
            "Explain superconducting magnet cooling.",
            "Why are cryogens used in a superconducting MRI magnet?",
            "To keep the conducting windings at a temperature with negligible electrical resistance",
            [
                "To suppress all radiofrequency noise in the scan room",
                "To slow hydrogen precession to an audible frequency",
                "To cool gradient coils between individual phase-encoding steps",
            ],
            "Very low temperatures allow the magnet windings to remain superconducting and sustain a large persistent current. Cryogens are not used to alter patient tissue resonance or image contrast.",
        ),
        q(
            "Distinguish transmit and receive hardware.",
            "Which statement about MRI radiofrequency coils is correct?",
            "A coil may be transmit-only, receive-only, or capable of both functions",
            [
                "Every surface coil must transmit and receive simultaneously",
                "Receiver coils create the spatial encoding gradients",
                "Transmit coils detect signal only after the gradients are disabled",
            ],
            "MRI systems use different coil designs according to anatomy and purpose; some transmit, some receive, and some do both. Receive-only arrays commonly improve local sensitivity while a separate body coil transmits.",
        ),
    ],
    "03.03": [
        q(
            "Relate nuclear spin to magnetic moment.",
            "What is the MRI-relevant consequence of a nucleus having nonzero spin?",
            "It behaves as a small magnetic moment that can interact with an external field",
            [
                "It becomes electrically neutral and cannot absorb energy",
                "It emits a continuous radiofrequency signal without excitation",
                "It aligns with every neighboring nucleus in the same direction",
            ],
            "A charged nucleus with nonzero angular momentum has a magnetic moment. That moment can occupy energy states, precess in B0, and interact with resonant RF energy.",
        ),
        q(
            "Distinguish equilibrium energy states.",
            "In the main magnetic field, which hydrogen proton orientation has lower energy?",
            "Parallel to B0",
            [
                "Antiparallel to B0",
                "Perpendicular to B0",
                "Randomly oriented in the transverse plane",
            ],
            "The parallel orientation is the lower-energy state and is therefore slightly more populated. The antiparallel state is higher energy, creating the small population imbalance responsible for net magnetization.",
        ),
        q(
            "Apply the Larmor relationship.",
            "Two hydrogen samples are placed in 1.5 T and 3 T magnets. How do their precession frequencies compare?",
            "The 3 T sample precesses at twice the frequency of the 1.5 T sample",
            [
                "The 3 T sample precesses at half the frequency of the 1.5 T sample",
                "Both samples precess at the same frequency because both contain hydrogen",
                "Their frequencies differ only after an RF pulse is applied",
            ],
            "Hydrogen's gyromagnetic ratio is constant, so Larmor frequency scales directly with B0. Doubling field strength from 1.5 T to 3 T doubles the resonance frequency.",
        ),
        q(
            "Explain RF resonance.",
            "What occurs when an RF pulse is applied at the Larmor frequency?",
            "Spins absorb energy and can become phase coherent while magnetization tips away from B0",
            [
                "Spins permanently stop precessing and align with the gradient field",
                "Longitudinal magnetization increases without transverse magnetization",
                "The tissue emits ionizing photons as antiparallel spins disappear",
            ],
            "A frequency-matched RF pulse transfers energy efficiently through resonance. It changes the population and phase relationships of spins, producing a measurable transverse component.",
        ),
        q(
            "Identify flip-angle controls.",
            "Which change can increase the flip angle when other sequence parameters are unchanged?",
            "Increasing the RF pulse amplitude or duration",
            [
                "Reducing the receiver bandwidth after the pulse",
                "Decreasing the phase-encoding matrix",
                "Increasing the field of view during readout",
            ],
            "Flip angle depends on the strength and duration of the applied B1 pulse. Receiver bandwidth, matrix, and field of view affect acquisition or spatial encoding rather than the excitation angle.",
        ),
    ],
    "03.04": [
        q(
            "Define T2 relaxation.",
            "Which process is responsible for T2 relaxation?",
            "Loss of transverse phase coherence from spin-spin interactions",
            [
                "Recovery of longitudinal magnetization through energy transfer to the lattice",
                "Spatial misregistration of fat and water during readout",
                "Replacement of transverse magnetization by a stronger gradient field",
            ],
            "T2 relaxation is transverse decay caused by microscopic spin-spin interactions that progressively dephase the spins. T1 describes longitudinal recovery and energy exchange with the surrounding lattice.",
        ),
        q(
            "Interpret the T2 time constant.",
            "At one tissue T2 time after excitation, approximately how much transverse magnetization remains?",
            "37%",
            [
                "63%",
                "50%",
                "10%",
            ],
            "T2 is the time required for transverse magnetization to decay to about 37% of its initial value. The complementary 63% figure is commonly associated with longitudinal recovery after one T1.",
        ),
        q(
            "Distinguish T2 from T2 star.",
            "Why does the free induction decay usually disappear faster than the tissue's true T2 decay?",
            "It includes both irreversible spin-spin dephasing and reversible field inhomogeneity effects",
            [
                "It measures only longitudinal recovery after the RF pulse",
                "It is acquired after all transverse magnetization has been refocused",
                "It excludes susceptibility and main-field variations",
            ],
            "The observed FID follows T2*, which combines intrinsic T2 decay with additional dephasing from B0 inhomogeneity and susceptibility. A spin echo can refocus much of the reversible component.",
        ),
        q(
            "Predict T2-weighted tissue signal.",
            "Which tissue property generally produces high signal on a strongly T2-weighted image?",
            "A long T2 with substantial transverse magnetization remaining at the echo",
            [
                "A short T2 with rapid transverse dephasing",
                "A short T1 with no transverse magnetization",
                "A low proton density combined with a long echo time",
            ],
            "Tissues with long T2 values retain transverse coherence later into the sequence and therefore generate more signal at a long TE. Free water is the classic example of a bright T2-weighted material.",
        ),
        q(
            "Explain spin-echo refocusing.",
            "What dephasing can a 180-degree refocusing pulse substantially reverse?",
            "Dephasing caused by static magnetic field differences",
            [
                "Irreversible molecular spin-spin interactions",
                "Longitudinal recovery caused by T1 relaxation",
                "Diffusion-related motion during every applied gradient",
            ],
            "The 180-degree pulse reverses the relative positions of faster and slower spins, allowing static frequency offsets to rephase at the echo. It cannot recover signal already lost through irreversible T2 interactions.",
        ),
    ],
    "03.05": [
        q(
            "Define T1 relaxation.",
            "Which description best characterizes T1 relaxation?",
            "Recovery of longitudinal magnetization through energy exchange with the surrounding lattice",
            [
                "Decay of transverse magnetization from spin-spin dephasing",
                "Loss of signal caused by spins leaving the selected slice",
                "Reversal of gradient-induced phase during readout",
            ],
            "T1, or spin-lattice relaxation, restores longitudinal magnetization as excited spins transfer energy to their environment. T2 is the distinct process of transverse phase decoherence.",
        ),
        q(
            "Interpret the T1 time constant.",
            "At one T1 time after a 90-degree excitation, approximately how much equilibrium longitudinal magnetization has recovered?",
            "63%",
            [
                "37%",
                "50%",
                "90%",
            ],
            "T1 is defined as the time required for longitudinal magnetization to recover to about 63% of equilibrium. The 37% value is the fraction of transverse magnetization remaining after one T2.",
        ),
        q(
            "Compare fat and water T1.",
            "Why is fat usually bright relative to simple fluid on a T1-weighted image?",
            "Fat has a shorter T1 and recovers longitudinal magnetization more rapidly",
            [
                "Fat has a longer T1 and remains saturated for less time",
                "Fat has no transverse relaxation after excitation",
                "Water cannot absorb RF energy at the hydrogen resonance frequency",
            ],
            "Fat's molecular environment permits relatively efficient spin-lattice energy exchange, giving it a short T1. It is therefore ready to contribute more signal when the next excitation occurs after a short TR.",
        ),
        q(
            "Relate field strength to T1.",
            "How does increasing the main magnetic field generally affect tissue T1 values?",
            "It lengthens T1 values",
            [
                "It shortens all T1 values to zero",
                "It leaves T1 unchanged while eliminating T2 decay",
                "It makes T1 equal to T2 in every tissue",
            ],
            "T1 values generally increase at higher field strengths because energy exchange at the higher Larmor frequency is less efficient for many tissues. The magnitude varies by tissue, but T1 does not become identical to T2.",
        ),
        q(
            "Compare T1 and T2 processes.",
            "Which statement correctly relates T1 and T2 relaxation after excitation?",
            "They occur simultaneously but describe different physical processes",
            [
                "T1 must finish before T2 can begin",
                "T2 restores longitudinal magnetization after T1 removes it",
                "They are two names for the same exponential decay",
            ],
            "Longitudinal recovery and transverse decay begin together after excitation, but they reflect different interactions. In biological tissues, T1 is usually longer than T2.",
        ),
    ],
    "03.06": [
        q(
            "Select T1-weighting parameters.",
            "Which combination produces conventional T1 weighting in a spin-echo acquisition?",
            "Short TR and short TE",
            [
                "Long TR and long TE",
                "Long TR and short TE",
                "Short TR and long TE",
            ],
            "A short TR preserves differences in longitudinal recovery, while a short TE minimizes competing T2 decay. This combination makes T1 differences the dominant source of contrast.",
        ),
        q(
            "Select T2-weighting parameters.",
            "Which combination produces conventional T2 weighting in a spin-echo acquisition?",
            "Long TR and long TE",
            [
                "Short TR and short TE",
                "Long TR and short TE",
                "Short TR and long TE",
            ],
            "A long TR minimizes T1 saturation differences, and a long TE allows tissues with different T2 values to separate. Long-T2 tissues retain more transverse signal at the echo.",
        ),
        q(
            "Select proton-density parameters.",
            "Which combination best emphasizes proton density in a spin-echo acquisition?",
            "Long TR and short TE",
            [
                "Short TR and short TE",
                "Long TR and long TE",
                "Short TR and long TE",
            ],
            "A long TR reduces T1 weighting and a short TE reduces T2 weighting. With both relaxation effects minimized, signal differences more closely reflect the number of mobile hydrogen protons.",
        ),
        q(
            "Explain TR-driven contrast.",
            "Why does a short repetition time increase T1 weighting?",
            "The next excitation occurs before tissues have fully recovered longitudinal magnetization",
            [
                "It allows all tissues to complete longitudinal recovery",
                "It increases transverse decay by delaying the echo",
                "It removes differences in spin-lattice recovery",
            ],
            "With short TR, tissues are re-excited at different points in their T1 recovery curves. Short-T1 tissues have recovered more and therefore generally produce more signal than long-T1 tissues.",
        ),
        q(
            "Explain TE-driven contrast.",
            "Why does a long echo time increase T2 weighting?",
            "It permits greater separation based on the rate of transverse decay",
            [
                "It forces all tissues to recover longitudinal magnetization",
                "It eliminates spin-spin interactions before signal collection",
                "It makes proton density the only remaining contrast source",
            ],
            "A long TE delays sampling so short-T2 tissues have lost much more transverse magnetization than long-T2 tissues. The resulting signal difference emphasizes T2 properties.",
        ),
        q(
            "Recognize mixed weighting.",
            "Why is a short-TR, long-TE spin-echo combination generally avoided for basic contrast weighting?",
            "It introduces competing T1 and T2 effects that can oppose one another",
            [
                "It removes both T1 and T2 contrast completely",
                "It is mathematically identical to proton-density weighting",
                "It prevents formation of any spin echo",
            ],
            "Short TR creates T1 weighting while long TE creates T2 weighting, and the tissue effects may pull signal in opposite directions. Standard protocols instead choose parameter pairs that emphasize one contrast mechanism cleanly.",
        ),
    ],
    "03.07": [
        q(
            "Explain slice-selective excitation.",
            "How does a slice-selection gradient localize RF excitation?",
            "It makes Larmor frequency vary with position so the RF bandwidth excites a defined spatial range",
            [
                "It makes every position precess at the same frequency",
                "It suppresses transverse magnetization outside the receiver bandwidth after readout",
                "It converts phase differences directly into image brightness",
            ],
            "During the slice gradient, position along the gradient corresponds to resonance frequency. The RF pulse excites only spins whose frequencies fall inside its transmitted bandwidth.",
        ),
        q(
            "Predict slice thickness from RF bandwidth.",
            "At a fixed slice-selection gradient strength, what is the effect of increasing RF pulse bandwidth?",
            "The selected slice becomes thicker",
            [
                "The selected slice becomes thinner",
                "The slice moves without changing thickness",
                "The slice thickness becomes independent of frequency",
            ],
            "A wider transmitted frequency range covers a larger position range when the frequency-versus-position slope is fixed. The result is a thicker excited slice.",
        ),
        q(
            "Predict slice thickness from gradient strength.",
            "At a fixed RF bandwidth, what is the effect of increasing the slice-selection gradient strength?",
            "The selected slice becomes thinner",
            [
                "The selected slice becomes thicker",
                "The slice shifts to isocenter without changing thickness",
                "The RF pulse excites the entire imaging volume",
            ],
            "A stronger gradient creates a steeper frequency change per unit distance. The same RF frequency range therefore spans a smaller distance and selects a thinner slice.",
        ),
        q(
            "Relate center frequency to slice position.",
            "With gradient strength and RF bandwidth unchanged, how is a different parallel slice selected?",
            "The center frequency of the RF pulse is changed",
            [
                "The receiver bandwidth is set to zero",
                "The phase-encoding matrix is doubled",
                "The echo time is lengthened",
            ],
            "Changing RF center frequency targets another position on the slice gradient's frequency map. Gradient amplitude and RF bandwidth chiefly determine the frequency-to-position slope and slice thickness.",
        ),
        q(
            "Identify the usual axial slice gradient.",
            "For a conventional axial acquisition, which physical gradient axis commonly performs slice selection?",
            "The z gradient",
            [
                "The x gradient only",
                "The y gradient only",
                "No gradient is required",
            ],
            "The z-axis runs along the bore and is perpendicular to a standard axial plane, so the z gradient commonly selects axial slices. Oblique imaging combines gradient axes as needed.",
        ),
    ],
    "03.08": [
        q(
            "Identify frequency-encoding timing.",
            "When is the frequency-encoding gradient applied?",
            "While the echo signal is being sampled",
            [
                "Only during the initial 90-degree RF pulse",
                "Between repetitions after all data have been stored",
                "Only while the phase-encoding gradient is at zero",
            ],
            "The readout gradient is active during signal acquisition, causing position along its axis to map to frequency. The sampled mixture of frequencies is later separated by Fourier transformation.",
        ),
        q(
            "Explain frequency localization.",
            "How are positions distinguished along the frequency-encoding direction?",
            "Spins at different positions precess at different frequencies during readout",
            [
                "Spins at different positions have permanently different T1 values",
                "Each position receives a separate 180-degree RF pulse",
                "Positions are distinguished only by receiver-coil size",
            ],
            "The readout gradient adds a position-dependent magnetic field and therefore a position-dependent Larmor frequency. Frequency analysis maps those signal components back to spatial locations.",
        ),
        q(
            "Relate sampling to frequency matrix.",
            "What primarily determines the number of reconstructed pixels along the frequency-encoding axis?",
            "The number of signal samples collected during readout",
            [
                "The number of phase-encoding repetitions",
                "The number of slice-selection RF pulses",
                "The number of receiver coils alone",
            ],
            "Each sampled time point contributes to the frequency-domain data used for the readout matrix. Phase-encoding steps determine resolution along the orthogonal phase axis.",
        ),
        q(
            "Relate dwell time and bandwidth.",
            "What happens to dwell time when receiver bandwidth per sampled point is increased?",
            "Dwell time becomes shorter",
            [
                "Dwell time becomes longer",
                "Dwell time remains fixed by T1",
                "Dwell time becomes equal to TR",
            ],
            "Dwell time is the interval between successive samples and is inversely related to sampling bandwidth. Faster sampling supports a wider receiver bandwidth.",
        ),
        q(
            "Identify the readout axis convention.",
            "In a conventional axial image, which gradient axis is commonly assigned to frequency encoding?",
            "The x axis",
            [
                "The z axis",
                "The longitudinal magnetization axis only",
                "The axis must always be identical to phase encoding",
            ],
            "With z used for axial slice selection, x is often selected as the readout direction and y as phase encoding. Frequency and phase assignments can be swapped for artifact control.",
        ),
    ],
    "03.09": [
        q(
            "Explain phase encoding.",
            "What information remains after the phase-encoding gradient is switched off?",
            "A position-dependent phase offset",
            [
                "A permanent position-dependent T1 change",
                "A different proton density at each location",
                "A continuous frequency difference caused by the absent gradient",
            ],
            "The gradient briefly changes precession frequency, causing spins at different positions to accumulate different phase. Once it is off, frequencies equalize but the phase offsets remain long enough to encode position.",
        ),
        q(
            "Identify phase-encoding repetition.",
            "Why is the pulse sequence repeated with multiple phase-encoding gradient amplitudes?",
            "Each amplitude acquires a different line of k-space",
            [
                "Each amplitude excites a different chemical element",
                "Each amplitude changes the main field to a new tesla value",
                "Each amplitude independently measures T1 without an echo",
            ],
            "A single readout cannot resolve both in-plane dimensions. Repeating the sequence with stepped phase encoding samples different spatial frequencies and fills successive k-space lines.",
        ),
        q(
            "Relate phase matrix to scan time.",
            "What is the usual effect of increasing the number of phase-encoding steps while TR and averages are unchanged?",
            "Scan time increases",
            [
                "Scan time decreases",
                "Scan time is unchanged because all steps occur simultaneously",
                "Only receiver bandwidth changes",
            ],
            "Each phase-encoding step generally requires another sequence repetition, so more phase lines increase acquisition time. This differs from adding readout samples, which are collected within one echo.",
        ),
        q(
            "Relate phase matrix to resolution.",
            "At a fixed phase field of view, what does increasing the phase matrix do?",
            "It improves phase-direction spatial resolution",
            [
                "It worsens phase-direction spatial resolution",
                "It increases slice thickness",
                "It removes all phase-direction motion artifact",
            ],
            "More phase samples divide the same field of view into smaller pixels, improving in-plane resolution. The tradeoffs include longer acquisition and lower signal per pixel.",
        ),
        q(
            "Identify central phase encoding.",
            "Which phase-encoding step contributes most directly to the center of k-space?",
            "The step with zero or very small phase-encoding amplitude",
            [
                "The step with the strongest positive gradient only",
                "The step with the longest receiver dwell time",
                "The step performed after longitudinal recovery is complete",
            ],
            "Low phase-encoding amplitudes represent low spatial frequencies and populate central k-space. Strong positive and negative steps populate progressively more peripheral lines.",
        ),
    ],
    "03.10": [
        q(
            "Interpret k-space samples.",
            "What does a single point in MRI k-space represent?",
            "A spatial-frequency contribution containing information from the entire image",
            [
                "The brightness of one corresponding image pixel",
                "The T1 value of one corresponding voxel",
                "A physical location occupied by one receiver coil",
            ],
            "K-space is a spatial-frequency domain, so every point contributes globally to the reconstructed image. A two-dimensional Fourier transform combines the complete dataset into image pixels.",
        ),
        q(
            "Identify central k-space information.",
            "Which image properties are most strongly determined by the center of k-space?",
            "Overall signal, contrast, and broad low-frequency structure",
            [
                "Fine edge detail only",
                "Slice position and RF center frequency only",
                "Chemical identity without image brightness",
            ],
            "Central k-space contains high-amplitude, low-spatial-frequency information that drives contrast and gross anatomy. It also contributes strongly to image signal-to-noise ratio.",
        ),
        q(
            "Identify peripheral k-space information.",
            "Which image property is most strongly associated with peripheral k-space?",
            "Fine detail and sharp edges",
            [
                "Overall contrast between large uniform tissues",
                "Longitudinal recovery before excitation",
                "Absolute main magnetic field strength",
            ],
            "Peripheral k-space stores high-spatial-frequency information, which defines rapid changes and edges. Removing peripheral data produces a smoother or blurrier image despite retaining broad contrast.",
        ),
        q(
            "Map acquisition dimensions to k-space.",
            "In a conventional two-dimensional acquisition, what typically selects successive k-space rows?",
            "Different phase-encoding gradient amplitudes",
            [
                "Different patient table positions during one echo",
                "Different RF coil diameters",
                "Different T1 values within the slice",
            ],
            "Readout samples traverse one k-space line while the phase-encoding amplitude sets that line's position in the orthogonal direction. Repetition with new phase steps fills the matrix.",
        ),
        q(
            "Explain k-space corruption timing.",
            "Motion during acquisition of central k-space is especially likely to alter which image feature?",
            "Image contrast and broad ghost structure",
            [
                "Only the highest-resolution edge pixels",
                "Only slice thickness",
                "Only the displayed field-strength label",
            ],
            "Central k-space contains much of the image's energy and contrast information, so corruption there has conspicuous global effects. Peripheral corruption more selectively degrades detail and sharpness.",
        ),
        q(
            "Explain partial k-space tradeoffs.",
            "What is a principal tradeoff when fewer than all planned k-space lines are acquired to shorten a scan?",
            "Reduced data can decrease SNR or create reconstruction-related loss of detail and artifact",
            [
                "T1 and T2 relaxation stop occurring",
                "The main magnet no longer needs shimming",
                "Every omitted line is replaced by an identical measured line",
            ],
            "Partial acquisition exploits k-space symmetry or reconstruction assumptions to save time. Because less independent data are measured, signal, resolution, or artifact performance may suffer.",
        ),
    ],
    "03.11": [
        q(
            "Calculate in-plane pixel size.",
            "How is pixel dimension along one in-plane axis determined?",
            "Field of view along that axis divided by the matrix along that axis",
            [
                "Matrix along that axis divided by field of view",
                "Slice thickness multiplied by receiver bandwidth",
                "Echo time divided by repetition time",
            ],
            "Dividing the physical field of view by the number of reconstructed samples gives pixel size. Smaller pixels can be obtained with a smaller FOV or a larger matrix.",
        ),
        q(
            "Define voxel dimensions.",
            "Which set of parameters defines the nominal voxel volume in a two-dimensional acquisition?",
            "Frequency pixel size, phase pixel size, and slice thickness",
            [
                "TR, TE, and flip angle",
                "Receiver bandwidth, dwell time, and averages",
                "B0 strength, B1 strength, and gradient slew rate",
            ],
            "A voxel is the three-dimensional tissue volume represented by a sample: two in-plane pixel dimensions times slice thickness. Sequence timing controls contrast rather than geometric voxel volume.",
        ),
        q(
            "Predict matrix tradeoffs.",
            "At fixed field of view, what is a major consequence of increasing the matrix?",
            "Smaller pixels improve spatial resolution but reduce signal per pixel",
            [
                "Larger pixels improve spatial resolution and SNR simultaneously",
                "Slice thickness automatically increases",
                "Chemical shift is eliminated without other changes",
            ],
            "A larger matrix divides the same field of view into smaller pixels, improving detail. Smaller sampled tissue volumes contain less signal, and increasing phase matrix also lengthens acquisition.",
        ),
        q(
            "Define receiver bandwidth.",
            "What does receiver bandwidth describe?",
            "The range of frequencies sampled during signal readout",
            [
                "The range of T1 values accepted into an image",
                "The RF frequencies transmitted during every phase step",
                "The physical width of the selected slice",
            ],
            "Receiver bandwidth defines the frequency range accepted and digitized during readout. It is related to sampling rate and dwell time, and it affects noise and frequency-direction artifacts.",
        ),
        q(
            "Relate bandwidth and dwell time.",
            "Which parameter combination is internally consistent?",
            "High receiver bandwidth with short dwell time",
            [
                "High receiver bandwidth with long dwell time",
                "Low receiver bandwidth with zero sampling interval",
                "Receiver bandwidth independent of sampling rate",
            ],
            "A wider frequency range requires faster sampling, so high bandwidth corresponds to a short interval between samples. Lower bandwidth permits longer dwell time.",
        ),
        q(
            "Predict FOV and resolution effects.",
            "At an unchanged matrix, what happens when the in-plane field of view is reduced?",
            "Pixel size decreases and spatial resolution improves",
            [
                "Pixel size increases and spatial resolution improves",
                "Pixel size is unchanged and slice thickness doubles",
                "Spatial resolution worsens while SNR always increases",
            ],
            "A smaller FOV divided by the same matrix yields smaller pixels and finer nominal resolution. SNR generally falls because each pixel contains less tissue, and wrap risk may increase.",
        ),
    ],
    "03.12": [
        q(
            "Relate bandwidth to image noise.",
            "Why does increasing receiver bandwidth reduce SNR?",
            "A wider frequency range admits more random noise",
            [
                "It prevents hydrogen from resonating",
                "It eliminates all transverse magnetization before readout",
                "It reduces the number of protons in the selected slice",
            ],
            "Noise is distributed across frequency, so a wider receiver window samples more noise power. Signal does not rise proportionally, causing SNR to decline.",
        ),
        q(
            "Apply the bandwidth-SNR relationship.",
            "If receiver bandwidth is reduced by a factor of two and other parameters are unchanged, how does SNR change approximately?",
            "It increases by the square root of two",
            [
                "It doubles",
                "It decreases by the square root of two",
                "It remains exactly unchanged",
            ],
            "SNR is approximately inversely proportional to the square root of receiver bandwidth. Halving bandwidth therefore raises SNR by about 1.41 rather than by a factor of two.",
        ),
        q(
            "Recognize high-bandwidth benefits.",
            "Which artifact is commonly reduced by increasing receiver bandwidth?",
            "Frequency-direction chemical shift",
            [
                "T1 saturation from a short TR",
                "Phase wrap caused solely by a small phase FOV",
                "Incomplete fat inversion in STIR",
            ],
            "Higher bandwidth maps a given fat-water frequency difference across fewer pixels, reducing type 1 chemical shift displacement. It can also reduce susceptibility distortion, at the cost of SNR.",
        ),
        q(
            "Recognize low-bandwidth tradeoffs.",
            "Which combination is most likely after lowering receiver bandwidth?",
            "Higher SNR with greater chemical shift and susceptibility-related distortion",
            [
                "Lower SNR with less chemical shift",
                "Higher SNR with a shorter dwell time",
                "No SNR change with complete artifact removal",
            ],
            "Lower bandwidth samples less noise and improves SNR, but its longer dwell time magnifies off-resonance displacement and distortion. Bandwidth selection therefore balances signal against artifact behavior.",
        ),
        q(
            "Relate bandwidth to sampling.",
            "What acquisition change accompanies an increase in receiver bandwidth?",
            "Faster sampling with a shorter readout interval",
            [
                "Slower sampling with a longer dwell time",
                "Fewer hydrogen nuclei in each voxel",
                "Mandatory use of a longer TR",
            ],
            "Wide bandwidth requires rapid sampling and short dwell time. This shortens the readout window and can reduce off-resonance distortion.",
        ),
    ],
    "03.13": [
        q(
            "Explain wraparound.",
            "What causes anatomy outside the selected field of view to appear on the opposite side of the image?",
            "Undersampling that makes outside and inside positions indistinguishable",
            [
                "Excessive longitudinal recovery that changes tissue contrast during a long TR",
                "Perfect refocusing that displaces spins after a 180-degree pulse",
                "Oversampling produced by a field of view larger than the patient",
            ],
            "When spatial frequencies are sampled below the Nyquist requirement, signals outside the FOV are assigned an incorrect in-field position. The result is aliasing or wraparound.",
        ),
        q(
            "Identify common phase-wrap control.",
            "Which adjustment directly reduces phase-direction wraparound?",
            "Increase phase coverage by phase oversampling or a larger phase FOV",
            [
                "Lengthen TE while keeping the phase sampling and field of view unchanged",
                "Reduce receiver bandwidth while leaving phase coverage unchanged",
                "Increase slice thickness without changing the phase sampling interval",
            ],
            "Phase oversampling acquires enough phase information to distinguish anatomy outside the nominal display FOV. A larger phase FOV can also include the anatomy but may reduce resolution unless matrix changes.",
        ),
        q(
            "Explain frequency oversampling.",
            "Why is frequency-direction wraparound often easier to prevent than phase-direction wraparound?",
            "Extra readout samples fit within the same echo without extra sequence repetitions",
            [
                "Frequency encoding uses no spatial gradient and therefore needs no extra sampling",
                "All anatomy has the same frequency during readout, preventing ambiguous positions",
                "Frequency oversampling reduces the number of receiver samples needed for reconstruction",
            ],
            "Readout oversampling adds data points within an existing acquisition window and can be filtered before reconstruction. Additional phase samples usually require more repetitions and therefore more time.",
        ),
        q(
            "Explain parallel imaging.",
            "How does parallel imaging reconstruct data omitted by phase undersampling?",
            "It uses distinct spatial sensitivity profiles from multiple receiver coils",
            [
                "It assumes omitted k-space lines contain the same values as adjacent measured lines",
                "It repeats the scan without gradients and substitutes that signal for phase data",
                "It replaces missing phase data with a map of independently measured T1 values",
            ],
            "Array coils view anatomy with different sensitivity profiles, providing extra spatial information that can separate aliased signals. Reconstruction combines that information with the undersampled k-space data.",
        ),
        q(
            "Identify parallel-imaging tradeoffs.",
            "What is a typical cost of increasing the parallel-imaging acceleration factor?",
            "Lower SNR and greater risk of reconstruction artifact",
            [
                "Longer scan time from additional phase steps",
                "Complete removal of coil sensitivity effects",
                "Higher SNR because less data are acquired",
            ],
            "Acceleration reduces the number of phase-encoding steps and shortens the scan, but less data and noise amplification reduce SNR. Calibration or coil-geometry limitations can create residual aliasing.",
        ),
    ],
    "03.14": [
        q(
            "Explain fat-water frequency difference.",
            "Why do fat protons resonate at a slightly lower frequency than water protons in the same main field?",
            "Electron shielding reduces the effective magnetic field experienced by fat protons",
            [
                "Fat protons have a different gyromagnetic ratio from hydrogen in water",
                "Water protons stop precessing during frequency encoding",
                "Fat contains no hydrogen outside the selected slice",
            ],
            "The molecular electron cloud shields fat protons slightly from B0, lowering their effective field and resonance frequency. The nuclei are still hydrogen and share the same gyromagnetic ratio.",
        ),
        q(
            "Relate chemical shift to field strength.",
            "How does the fat-water frequency separation in hertz change when field strength increases?",
            "It increases in direct proportion to field strength",
            [
                "It decreases in inverse proportion to field strength",
                "It remains constant in hertz at all fields",
                "It disappears above 1.5 T",
            ],
            "The chemical shift is approximately constant in parts per million, but the underlying Larmor frequency rises with B0. The absolute separation in hertz therefore increases at higher field.",
        ),
        q(
            "Identify type 1 chemical shift.",
            "Where does spatial misregistration of fat relative to water appear?",
            "Along the frequency-encoding direction",
            [
                "Only along the slice-selection direction",
                "Only along the phase-encoding direction regardless of readout",
                "Equally in all directions without relation to gradients",
            ],
            "Type 1 chemical shift occurs because the reconstruction interprets fat's frequency offset as a position offset along readout. Swapping frequency and phase directions moves the artifact accordingly.",
        ),
        q(
            "Reduce chemical shift displacement.",
            "Which change reduces the pixel displacement from type 1 chemical shift?",
            "Increase receiver bandwidth",
            [
                "Decrease receiver bandwidth",
                "Increase TE without changing bandwidth",
                "Increase the phase matrix only",
            ],
            "A wider bandwidth assigns more hertz to each pixel, so the fixed fat-water frequency difference spans fewer pixels. The tradeoff is reduced SNR.",
        ),
        q(
            "Recognize opposed-phase cancellation.",
            "What produces a dark outline at fat-water interfaces on an opposed-phase image?",
            "Cancellation of fat and water signals within the same voxel",
            [
                "Spatial wrap of anatomy outside the phase FOV",
                "Failure of the 180-degree pulse to refocus static inhomogeneity",
                "Loss of all longitudinal magnetization in pure fat",
            ],
            "When fat and water magnetization are opposed in a mixed voxel, their transverse signals subtract and may cancel. This type 2 chemical shift effect is often called the India-ink artifact.",
        ),
    ],
    "03.15": [
        q(
            "Describe spin-echo timing.",
            "In a conventional spin-echo sequence, when is the 180-degree pulse applied relative to the echo?",
            "Halfway between the 90-degree excitation and the echo",
            [
                "At the same instant as the 90-degree excitation",
                "After the echo has already been sampled",
                "One full repetition time before excitation",
            ],
            "The 180-degree pulse is applied at TE/2 so that static frequency offsets rephase at TE. This timing creates the spin echo while preserving irreversible T2 decay.",
        ),
        q(
            "Distinguish spin echo from gradient echo.",
            "What is the principal purpose of the 180-degree pulse in a spin-echo sequence?",
            "To refocus dephasing caused by static field inhomogeneity",
            [
                "To restore signal lost through irreversible T2 interactions",
                "To select the phase-encoding matrix",
                "To create a permanent increase in B0",
            ],
            "The refocusing pulse reverses phase dispersion from stable frequency differences, producing an echo governed more closely by true T2. It cannot reverse microscopic spin-spin relaxation.",
        ),
        q(
            "Explain multiecho imaging.",
            "How does a multiecho spin-echo sequence obtain signals at more than one TE after a single excitation?",
            "It applies multiple 180-degree refocusing pulses",
            [
                "It applies multiple slice-selection gradients without refocusing",
                "It changes the main field between receiver samples",
                "It uses one RF pulse and records only the free induction decay",
            ],
            "Repeated refocusing pulses generate a train of spin echoes at progressively longer echo times. Those echoes can provide different T2 weighting or populate multiple k-space lines.",
        ),
        q(
            "Explain multislice efficiency.",
            "How can multiple slices be acquired within one repetition interval?",
            "Excitations and echoes for different slices are interleaved while other slices recover",
            [
                "Every slice is assigned the same RF center frequency",
                "The slice gradient is omitted after the first slice",
                "All slices are compressed into one phase-encoding line",
            ],
            "After one slice is excited, the system can excite and collect data from other slices during otherwise unused recovery time. Slice-selective frequencies and gradients keep the signals spatially distinct.",
        ),
        q(
            "Explain fast spin echo.",
            "How does fast spin echo shorten acquisition compared with conventional spin echo?",
            "Multiple echoes after one excitation fill multiple k-space lines",
            [
                "One echo is copied into every k-space line",
                "The phase-encoding gradient is eliminated",
                "All 180-degree pulses are replaced by a longer TR",
            ],
            "An echo train uses a different phase-encoding value for each refocused echo, collecting several lines per TR. The echo train length therefore reduces the number of required repetitions.",
        ),
        q(
            "Define effective TE in fast spin echo.",
            "What determines the effective TE of a fast spin-echo image?",
            "The echo time of the signal used to fill central k-space",
            [
                "The time of the final echo regardless of k-space order",
                "The interval between adjacent slice excitations",
                "The duration of the receiver's first dwell interval",
            ],
            "Contrast is dominated by central k-space, so the echo assigned there defines effective TE. Other echoes fill more peripheral lines and influence detail and blurring.",
        ),
    ],
    "03.16": [
        q(
            "Identify gradient-echo formation.",
            "How is the echo formed in a basic gradient-echo sequence?",
            "By reversing a dephasing gradient to rephase transverse magnetization",
            [
                "By applying a 180-degree refocusing RF pulse",
                "By waiting for complete T1 recovery",
                "By switching off the main magnetic field",
            ],
            "Gradient echo uses gradient polarity reversal rather than a 180-degree RF pulse to bring spins back into phase. This permits shorter TR and TE values.",
        ),
        q(
            "Explain T2-star sensitivity.",
            "Why is gradient-echo signal described by T2-star rather than true T2?",
            "Static field inhomogeneity is not refocused by a 180-degree pulse",
            [
                "Spin-spin interactions are completely eliminated by gradient reversal",
                "Longitudinal recovery is measured without transverse signal",
                "Receiver bandwidth is always zero",
            ],
            "Gradient reversal refocuses gradient-induced phase but does not remove dephasing from susceptibility and B0 variation. The measured decay therefore includes both T2 and inhomogeneity effects.",
        ),
        q(
            "Recognize gradient-echo speed.",
            "Which feature allows gradient-echo sequences to use very short repetition times?",
            "Small flip angles leave more longitudinal magnetization available for repeated excitation",
            [
                "A mandatory 180-degree pulse restores all longitudinal magnetization",
                "Every tissue completes T1 recovery before the next pulse",
                "Phase encoding is unnecessary in gradient echo",
            ],
            "A partial flip uses only part of the longitudinal magnetization, limiting saturation during rapid repetitions. Omitting the 180-degree pulse also reduces RF energy and sequence duration.",
        ),
        q(
            "Compare RF energy deposition.",
            "Compared with a similar spin-echo acquisition, why can gradient echo have lower RF power deposition?",
            "It omits the repeated 180-degree refocusing pulses",
            [
                "It uses a stronger static magnetic field for every patient",
                "It eliminates all RF excitation",
                "It requires twice as many phase-encoding steps",
            ],
            "High-flip-angle refocusing trains contribute substantially to specific absorption rate. Gradient echo generally uses one lower-flip excitation and gradient-based rephasing.",
        ),
        q(
            "Recognize susceptibility effects.",
            "Which finding is gradient-echo imaging especially sensitive to?",
            "Local susceptibility differences from blood products or metal",
            [
                "Only longitudinal recovery in uniform water",
                "Complete cancellation of all off-resonance effects",
                "Slice wrap caused solely by a long TR",
            ],
            "Without a 180-degree refocusing pulse, local field variations cause prominent signal loss and blooming. This sensitivity is useful for blood products but can be problematic near metal or air.",
        ),
    ],
    "03.17": [
        q(
            "Define the Ernst angle.",
            "What does the Ernst angle optimize?",
            "Steady-state signal for a tissue with a given T1 and repetition time",
            [
                "The shortest possible T2 for every tissue",
                "The maximum gradient strength before quenching",
                "The chemical shift between fat and water",
            ],
            "The Ernst angle balances signal used by each excitation against longitudinal recovery before the next one. Its optimum is tissue- and TR-dependent rather than universal.",
        ),
        q(
            "Apply the Ernst relationship.",
            "For a fixed tissue T1, how does increasing TR affect the Ernst angle?",
            "The optimal flip angle becomes larger",
            [
                "The optimal flip angle becomes smaller",
                "The optimal flip angle remains zero",
                "The optimal flip angle becomes independent of recovery",
            ],
            "Longer TR permits more longitudinal recovery, so a larger fraction can be tipped without excessive steady-state saturation. At very short TR values, a smaller flip can produce more steady-state signal than a larger one.",
        ),
        q(
            "Relate T1 to optimal flip angle.",
            "At a fixed short TR, which tissue generally has the larger Ernst angle?",
            "The tissue with the shorter T1",
            [
                "The tissue with the longer T1",
                "Both tissues because Ernst angle is always 90 degrees",
                "Neither tissue because flip angle affects only T2",
            ],
            "Short-T1 tissue replenishes longitudinal magnetization more rapidly between pulses and can support a larger optimal flip. Long-T1 tissue remains more saturated at the same TR.",
        ),
        q(
            "Explain small-flip-angle benefit.",
            "Why can a small flip angle produce more steady-state signal than a 90-degree pulse when TR is very short?",
            "It preserves longitudinal magnetization for subsequent excitations",
            [
                "It eliminates the need for transverse magnetization",
                "It doubles proton density inside the voxel",
                "It lengthens TR without changing the sequence timing",
            ],
            "A 90-degree pulse exhausts the available longitudinal component and severe saturation follows when recovery time is short. A smaller flip sacrifices some immediate signal but leaves magnetization for repeated acquisitions.",
        ),
        q(
            "Identify flip-angle controls.",
            "Which pair directly determines flip angle for a rectangular RF pulse?",
            "RF field amplitude and pulse duration",
            [
                "Field of view and phase matrix",
                "Echo time and receiver bandwidth",
                "Slice thickness and number of averages",
            ],
            "Flip angle is proportional to the time integral of B1, so increasing amplitude or duration increases the rotation. Imaging geometry and readout settings do not directly set the excitation angle.",
        ),
    ],
    "03.18": [
        q(
            "Distinguish spoiled gradient echo.",
            "What is the purpose of spoiling in a gradient-echo sequence?",
            "To destroy residual transverse coherence before the next excitation",
            [
                "To eliminate longitudinal magnetization permanently",
                "To refocus susceptibility dephasing into a true spin echo",
                "To increase the fat-water frequency difference",
            ],
            "RF or gradient spoiling prevents leftover transverse magnetization from contributing coherently to later signals. The resulting contrast is dominated more predictably by T1 and the fresh excitation.",
        ),
        q(
            "Describe coherent gradient echo.",
            "What distinguishes a coherent gradient-echo sequence?",
            "Residual transverse magnetization is preserved and refocused across repetitions",
            [
                "All transverse magnetization is deliberately randomized after every readout",
                "Only longitudinal recovery contributes to signal",
                "A 180-degree pulse removes every off-resonance effect",
            ],
            "Coherent sequences retain and reuse transverse components, allowing multiple echo pathways and steady-state behavior. This differs from spoiled sequences that intentionally erase that history.",
        ),
        q(
            "Recognize balanced SSFP.",
            "Which feature is characteristic of balanced steady-state free precession?",
            "All gradient moments are balanced within each repetition",
            [
                "No gradients are applied",
                "Residual transverse magnetization is completely spoiled",
                "A long TR allows full recovery before every pulse",
            ],
            "Balanced gradients return stationary spins to the same phase position after each TR, sustaining a high-signal steady state. The method is rapid and produces contrast related to the T2/T1 ratio.",
        ),
        q(
            "Identify SSFP appearance.",
            "Which tissue or structure is often conspicuously bright on balanced SSFP images?",
            "Fluid or blood with a high T2-to-T1 ratio",
            [
                "Cortical bone with almost no mobile protons",
                "Air with no detectable hydrogen signal",
                "Metal because susceptibility is fully corrected",
            ],
            "Balanced SSFP provides high signal efficiency and favors tissues with a high T2/T1 ratio, including many fluids and blood. Bone and air remain low signal.",
        ),
        q(
            "Recognize SSFP artifact.",
            "What artifact commonly results from off-resonance in balanced SSFP?",
            "Dark banding",
            [
                "Pure phase wrap independent of FOV",
                "Complete fat suppression at every field strength",
                "A uniform doubling of slice thickness",
            ],
            "Balanced SSFP signal varies periodically with off-resonance frequency, creating dark bands where local field offsets fall at signal nulls. Good shimming and shorter TR reduce this problem.",
        ),
        q(
            "Explain stimulated echoes.",
            "How is magnetization stored during formation of a stimulated echo?",
            "An RF pulse places part of the transverse coherence along the longitudinal axis",
            [
                "A gradient permanently removes the longitudinal component",
                "The receiver converts T2 decay directly into B0",
                "A single 180-degree pulse eliminates all prior phase information",
            ],
            "A sequence of RF pulses can convert transverse phase information into longitudinal magnetization and later return it to the transverse plane. This stored pathway produces a stimulated echo with different relaxation behavior.",
        ),
    ],
    "03.19": [
        q(
            "Describe inversion-recovery preparation.",
            "What is the initial RF pulse in a conventional inversion-recovery sequence?",
            "A 180-degree inversion pulse",
            [
                "A 30-degree readout pulse",
                "A 90-degree saturation pulse only",
                "A frequency-encoding gradient with no RF",
            ],
            "Inversion recovery begins by flipping longitudinal magnetization through 180 degrees. After the inversion time, an excitation pulse samples the tissue-dependent recovery.",
        ),
        q(
            "Explain tissue nulling.",
            "When is a tissue nulled in an inversion-recovery sequence?",
            "The excitation pulse occurs when that tissue's longitudinal magnetization crosses zero",
            [
                "The echo occurs after all tissues complete T2 decay",
                "The receiver bandwidth excludes the tissue's proton density",
                "The tissue reaches maximum positive longitudinal magnetization",
            ],
            "At the zero crossing, the tissue has no longitudinal component to tip into the transverse plane, so it produces little signal. TI is selected according to the target tissue's T1.",
        ),
        q(
            "Identify STIR target.",
            "Which tissue is intentionally suppressed by short-tau inversion recovery?",
            "Fat",
            [
                "Cerebrospinal fluid",
                "Cortical bone only",
                "All gadolinium-containing tissue exclusively",
            ],
            "STIR uses a short inversion time chosen to place fat at its longitudinal null. It provides robust fat suppression even when frequency-selective methods are degraded by field inhomogeneity.",
        ),
        q(
            "Identify FLAIR target.",
            "Which material is intentionally suppressed by fluid-attenuated inversion recovery?",
            "Cerebrospinal fluid",
            [
                "Fat",
                "Flowing arterial blood only",
                "Calcium",
            ],
            "FLAIR uses a long inversion time to null CSF while retaining T2 weighting in brain tissue. Lesions with prolonged T2 can remain bright next to dark CSF.",
        ),
        q(
            "Recognize postcontrast STIR limitation.",
            "Why is STIR generally avoided for selective fat suppression after gadolinium administration?",
            "It nulls tissue by T1 rather than chemical identity and can suppress enhancing tissue",
            [
                "Gadolinium removes all hydrogen from fat",
                "STIR requires a receiver bandwidth of zero",
                "Gadolinium makes fat and water precess at identical frequencies",
            ],
            "STIR suppresses any tissue whose T1 reaches the chosen null, not fat specifically. Gadolinium shortens T1, so enhancing lesions may lose signal and become less conspicuous.",
        ),
        q(
            "Recognize inversion-recovery tradeoffs.",
            "What is a typical cost of inversion-recovery preparation?",
            "Longer acquisition and reduced signal efficiency",
            [
                "Loss of all T1 contrast",
                "Inability to use slice selection",
                "Mandatory phase wrap in every direction",
            ],
            "The inversion pulse and recovery delay add time, and the target tissue is deliberately suppressed. In return, inversion recovery provides strong T1-based contrast and selective nulling.",
        ),
    ],
    "03.20": [
        q(
            "Define partial saturation.",
            "What produces partial saturation in a repeatedly excited tissue?",
            "Incomplete longitudinal recovery before the next RF pulse",
            [
                "The echo is sampled after transverse magnetization fully refocuses",
                "The phase gradient is applied after complete T1 recovery",
                "The receiver accepts only frequencies outside the tissue",
            ],
            "A short TR leaves incomplete longitudinal recovery, so repeated excitation reduces available magnetization. Tissues with different T1 values saturate to different degrees.",
        ),
        q(
            "Explain spatial saturation bands.",
            "How does a spatial saturation band suppress signal from inflowing tissue?",
            "An RF pulse excites the band and a spoiler dephases its transverse magnetization before it enters the imaging region",
            [
                "A 180-degree pulse permanently removes spins from the bloodstream",
                "A smaller field of view excludes all moving protons",
                "The receiver bandwidth is centered on stationary tissue only",
            ],
            "Spatially selective saturation prepares tissue outside the imaging volume so it arrives with reduced longitudinal magnetization. Spoiling prevents coherent signal from the prepared band.",
        ),
        q(
            "Explain CHESS fat suppression.",
            "What makes CHESS suppression selective for fat?",
            "A narrow RF pulse is centered on the fat resonance frequency",
            [
                "A short inversion time nulls every tissue with a similar T1",
                "A gradient distinguishes fat solely by spatial position",
                "A long TE removes water while preserving fat",
            ],
            "Chemical-shift selective saturation exploits the frequency separation between fat and water. A fat-selective pulse followed by spoiling removes fat transverse signal while largely sparing water.",
        ),
        q(
            "Recognize CHESS limitations.",
            "Why can frequency-selective fat saturation fail near metal or at the edge of the magnet?",
            "B0 inhomogeneity shifts local fat and water resonance frequencies",
            [
                "Fat loses its hydrogen nuclei near metal",
                "T1 and T2 become identical in inhomogeneous fields",
                "The phase matrix becomes independent of gradients",
            ],
            "CHESS assumes predictable fat and water frequencies. Local off-resonance can move fat outside the saturation pulse or inadvertently suppress water.",
        ),
        q(
            "Compare CHESS with STIR after contrast.",
            "Which fat-suppression method is generally preferred when preserving gadolinium enhancement is important?",
            "Frequency-selective fat saturation such as CHESS",
            [
                "STIR with a fat-null inversion time",
                "A saturation band placed over the lesion",
                "No RF excitation followed by a long TE",
            ],
            "CHESS targets fat by resonance frequency and does not inherently suppress all short-T1 enhancing tissue. STIR is nonspecific T1 nulling and may reduce gadolinium-related lesion signal.",
        ),
    ],
    "03.21": [
        q(
            "Explain EPI speed.",
            "Why can echo-planar imaging acquire an image extremely rapidly?",
            "Rapid gradient reversals traverse many or all k-space lines after one excitation",
            [
                "Every k-space point is assumed to have the same value",
                "T1 and T2 relaxation are suspended during acquisition",
                "A separate 90-degree pulse is used for every image pixel",
            ],
            "EPI uses a train of gradient echoes and blipped phase encoding to cover k-space with very few RF excitations. Single-shot EPI can collect the entire matrix in one echo train.",
        ),
        q(
            "Identify EPI applications.",
            "Which acquisition commonly relies on echo-planar readout because temporal speed is critical?",
            "Diffusion-weighted imaging",
            [
                "A conventional multiminute spin-echo localizer only",
                "Static-field shimming without image acquisition",
                "A proton-density scan requiring no gradients",
            ],
            "DWI commonly uses single-shot EPI to freeze motion and rapidly collect diffusion-sensitive data. Functional and perfusion MRI also benefit from EPI's temporal resolution.",
        ),
        q(
            "Recognize EPI limitations.",
            "Which artifact combination is characteristic of echo-planar imaging?",
            "Susceptibility distortion and phase ghosting",
            [
                "Complete elimination of off-resonance distortion",
                "Only T1 saturation with no geometric effects",
                "Loss of all low-spatial-frequency information",
            ],
            "The long, rapidly sampled EPI echo train is highly sensitive to field offsets, eddy currents, and timing errors. These effects produce geometric distortion, signal loss, and ghosting.",
        ),
        q(
            "Explain fast spin-echo acceleration.",
            "What does each echo in a fast spin-echo train usually contribute?",
            "A differently phase-encoded k-space line",
            [
                "An identical copy of the same image pixel",
                "A new main magnetic field strength",
                "A separate slice with no spatial encoding",
            ],
            "Changing phase encoding between refocused echoes lets one excitation populate multiple k-space lines. Echo train length is therefore a major determinant of acceleration.",
        ),
        q(
            "Compare FSE with EPI.",
            "Compared with single-shot EPI, what is a typical advantage of fast spin echo?",
            "Less susceptibility-related geometric distortion",
            [
                "Shorter acquisition than every EPI sequence",
                "No RF energy deposition from refocusing pulses",
                "Complete immunity to motion and blurring",
            ],
            "FSE's 180-degree pulse train refocuses much static inhomogeneity and generally produces less distortion than EPI. It is slower and can have high SAR and echo-train blurring.",
        ),
        q(
            "Recognize FSE tradeoffs.",
            "What can result from a very long fast spin-echo train?",
            "Image blurring as different k-space lines experience different T2 decay",
            [
                "Elimination of T2 effects from all echoes",
                "A mandatory increase in chemical shift frequency",
                "Perfect recovery of signal lost to molecular interactions",
            ],
            "Signal amplitude changes across the echo train because of T2 decay, so k-space is weighted unevenly. Long trains accelerate imaging but can soften edges and increase RF power deposition.",
        ),
    ],
    "03.22": [
        q(
            "Explain diffusion sensitization.",
            "Why does freely diffusing water lose signal after paired diffusion-sensitizing gradients?",
            "Random motion prevents complete rephasing by the gradient pair",
            [
                "All moving spins leave the body before the second gradient",
                "Diffusion permanently eliminates longitudinal magnetization",
                "The second gradient always has the same polarity as the first",
            ],
            "Stationary spins experience equal and opposite gradient effects and rephase. Diffusing spins change position between lobes, accumulate residual phase dispersion, and lose coherent signal.",
        ),
        q(
            "Recognize true restriction.",
            "Which signal pattern supports true restricted diffusion?",
            "High signal on high-b-value DWI and low signal on the ADC map",
            [
                "Low signal on DWI and high signal on ADC",
                "High signal on both DWI and ADC",
                "Low signal on both DWI and ADC from every T2-bright lesion",
            ],
            "Restriction limits molecular displacement, preserving high-b DWI signal while producing a low calculated ADC. This combination helps distinguish restriction from T2-related brightness.",
        ),
        q(
            "Recognize T2 shine-through.",
            "What finding suggests that DWI hyperintensity is caused by T2 shine-through rather than restriction?",
            "The ADC is not reduced",
            [
                "The ADC is markedly reduced",
                "The lesion is dark on every T2-weighted image",
                "The b-value is greater than zero",
            ],
            "A long-T2 lesion can remain bright on DWI even without limited diffusion. Its ADC remains normal or high, whereas true restriction lowers ADC.",
        ),
        q(
            "Interpret b-value.",
            "What happens when the diffusion b-value is increased?",
            "Diffusion weighting increases while image SNR generally decreases",
            [
                "Diffusion weighting decreases while SNR always increases",
                "T1 weighting becomes the only contrast mechanism",
                "The ADC calculation becomes independent of signal",
            ],
            "Higher b-values strengthen or lengthen the sensitizing gradients and make signal more dependent on molecular motion. More diffusion-related attenuation also leaves less signal and lowers SNR.",
        ),
        q(
            "Explain ADC calculation.",
            "Why are at least two b-values used to calculate an apparent diffusion coefficient?",
            "Signal decay across different diffusion weightings is needed to estimate diffusivity",
            [
                "One b-value measures T1 and the other measures slice thickness",
                "The second b-value removes the need for spatial encoding",
                "ADC is the arithmetic mean of two field strengths",
            ],
            "ADC is derived from the logarithmic signal change as diffusion weighting changes. A single diffusion-weighted signal cannot separate baseline signal intensity from the attenuation rate.",
        ),
        q(
            "Recognize diffusion anisotropy.",
            "What does diffusion anisotropy mean?",
            "Measured diffusivity depends on the direction of the applied gradients",
            [
                "Diffusivity is identical in every direction",
                "Only longitudinal relaxation changes with direction",
                "Water diffusion occurs only when RF is off",
            ],
            "Ordered structures such as white-matter tracts permit easier water motion along some directions than others. Directional diffusion measurements form the basis of diffusion tensor imaging.",
        ),
    ],
    "03.23": [
        q(
            "Explain high-velocity signal loss.",
            "Why can rapidly flowing blood be dark on a spin-echo image?",
            "Excited spins may leave the slice before the refocusing pulse or echo is received",
            [
                "Blood contains no hydrogen to excite",
                "Flowing spins always have a T1 of zero",
                "The receiver rejects all frequencies produced by motion",
            ],
            "Spin echo requires spins to experience the excitation, refocusing pulse, and readout within the selected slice. Fast flow can carry them away before refocusing, producing a flow void.",
        ),
        q(
            "Relate flow void to slice geometry.",
            "Which change makes through-plane high-velocity signal loss less likely?",
            "Use a thicker slice or shorter time to the refocusing pulse",
            [
                "Use a thinner slice and lengthen the time to the refocusing pulse",
                "Increase the number of phase steps only",
                "Lengthen the interval before the refocusing pulse",
            ],
            "A thicker slice gives moving blood farther to travel before leaving, and earlier refocusing gives it less time to escape. Thin slices and long delays make loss of the required 180-degree pulse more likely.",
        ),
        q(
            "Explain intravoxel dephasing.",
            "Why can turbulent or complex flow cause signal loss even when blood remains inside the slice?",
            "Different velocities and directions create a broad distribution of phases within the voxel",
            [
                "All spins acquire exactly the same phase",
                "Turbulence eliminates the applied gradients",
                "The tissue's proton density becomes zero",
            ],
            "A voxel containing many velocities accumulates inconsistent phase shifts during gradients. Their vector signals cancel, causing intravoxel dephasing and dark signal.",
        ),
        q(
            "Recognize time-of-flight effects.",
            "Which factors most directly influence whether flowing spins remain available for a spin echo?",
            "Flow velocity, slice thickness, and echo timing",
            [
                "Display window, monitor brightness, and image annotation",
                "Only patient age and magnet manufacturer",
                "Phase matrix alone, independent of motion direction",
            ],
            "Signal depends on whether spins traverse the excited slice before refocusing and readout. Their speed, travel distance through the slice, and elapsed time therefore matter.",
        ),
        q(
            "Compare bright-blood behavior.",
            "Why can gradient-echo imaging show inflowing blood as bright?",
            "Fresh spins enter with relatively unsaturated longitudinal magnetization and no 180-degree pulse is required",
            [
                "Flowing blood is permanently phase locked to stationary tissue",
                "Gradient echo suppresses all inflow effects",
                "Blood has a higher gyromagnetic ratio than tissue hydrogen",
            ],
            "Repeated short-TR excitation saturates stationary tissue, while fresh blood entering the slice can produce stronger signal. Gradient echo does not require the same spin to remain for a later 180-degree pulse.",
        ),
    ],
    "03.24": [
        q(
            "Explain TOF contrast.",
            "What creates vessel-to-background contrast in time-of-flight MR angiography?",
            "Fresh inflowing blood is less saturated than stationary tissue",
            [
                "Gadolinium selectively shortens blood T1 during every TOF acquisition",
                "Stationary tissue receives fewer RF pulses than blood entering the slab",
                "Velocity-dependent phase subtraction makes inflowing blood bright",
            ],
            "A short-TR gradient-echo sequence repeatedly saturates tissue within the slab. Spins flowing into it arrive with more longitudinal magnetization and therefore appear bright.",
        ),
        q(
            "Recognize TOF signal loss.",
            "Which condition can make a patent vessel appear falsely dark on TOF MRA?",
            "Slow in-plane flow that becomes saturated in the imaging slab",
            [
                "Rapid perpendicular inflow that continually supplies fresh spins",
                "A saturation band correctly placed over only undesired venous inflow",
                "A short-TR gradient echo with rapid replacement of blood spins",
            ],
            "Blood that remains in the slab for many RF pulses loses the inflow advantage and becomes saturated. Slow flow and flow parallel to the slab are therefore vulnerable to signal loss.",
        ),
        q(
            "Compare 2D and 3D TOF.",
            "Why can two-dimensional TOF be advantageous for slow flow over a long anatomic region?",
            "Thin independently excited slices limit saturation of entering spins",
            [
                "A thick three-dimensional slab prevents repeated excitation of slow blood",
                "Two-dimensional TOF avoids RF excitation of both blood and stationary tissue",
                "Two-dimensional TOF measures slow velocity through phase subtraction",
            ],
            "Each thin 2D slice has a short transit distance, reducing saturation of slowly moving spins. Three-dimensional TOF offers higher spatial resolution but is more susceptible to saturation across a thick slab.",
        ),
        q(
            "Use saturation bands.",
            "How can a saturation band help isolate arterial flow in TOF imaging?",
            "Place it on the venous inflow side to suppress entering venous spins",
            [
                "Place it on the arterial inflow side to increase arterial saturation",
                "Apply it to every voxel after reconstruction to remove background",
                "Use it to alter the gyromagnetic ratio of blood entering from one direction",
            ],
            "A directional saturation band pre-saturates spins entering from the undesired direction. Placement must reflect flow direction so the target arterial inflow remains fresh.",
        ),
        q(
            "Recognize TOF postprocessing.",
            "What does a maximum-intensity projection do to a TOF volume?",
            "Displays the highest-signal voxel along each viewing ray",
            [
                "Calculates ADC from multiple b-values",
                "Subtracts phase in stationary tissue only",
                "Converts all dark tissue to a gadolinium concentration",
            ],
            "MIP compresses a three-dimensional bright-vessel dataset into projection images by selecting maximum voxel intensity. Overlap or bright background structures can obscure vessels, so source images remain important.",
        ),
    ],
    "03.25": [
        q(
            "Explain motion-induced phase.",
            "Why can a moving spin retain phase after a balanced gradient pair that rephases stationary spins?",
            "It occupies different positions during the two gradient lobes",
            [
                "It has a different hydrogen gyromagnetic ratio",
                "It cannot experience magnetic gradients",
                "It completes T1 recovery during the first lobe",
            ],
            "Stationary spins experience equal and opposite gradient areas at one location. Moving spins sample different field strengths over time, so the phase effects do not perfectly cancel.",
        ),
        q(
            "Define gradient moment nulling.",
            "What is the goal of first-order gradient moment nulling?",
            "To rephase spins moving at constant velocity",
            [
                "To suppress every stationary spin",
                "To calculate proton density without an echo",
                "To correct motion with arbitrary acceleration and turbulence",
            ],
            "Additional gradient lobes are designed so both stationary and constant-velocity spins have zero net phase at the echo. Higher-order or complex motion is not fully corrected.",
        ),
        q(
            "Recognize flow-compensation benefit.",
            "What image effect can flow compensation reduce?",
            "Phase dispersion and ghosting from smoothly moving blood or CSF",
            [
                "T1 saturation caused by short TR",
                "Chemical shift caused by fat-water resonance differences",
                "Aliasing caused by an undersized field of view",
            ],
            "Gradient moment nulling reduces coherent motion-related phase shifts and can restore signal in vessels or CSF. It does not correct unrelated sampling or chemical-shift artifacts.",
        ),
        q(
            "Recognize flow-compensation cost.",
            "What is a common tradeoff of adding gradient moment nulling?",
            "Longer minimum TE",
            [
                "Elimination of all gradient switching",
                "Mandatory reduction of field strength",
                "Complete loss of stationary tissue signal",
            ],
            "The extra gradient lobes require time and can lengthen the minimum echo time. That may increase T2-star or motion-related signal loss in other parts of the sequence.",
        ),
        q(
            "Recognize limitations of compensation.",
            "Which flow pattern is least likely to be fully corrected by first-order gradient moment nulling?",
            "Accelerating or turbulent flow",
            [
                "Stationary tissue",
                "Constant-velocity laminar flow",
                "A static phantom at isocenter",
            ],
            "First-order compensation assumes constant velocity. Acceleration, pulsatility, and turbulence introduce higher-order and intravoxel phase behavior that remains uncorrected.",
        ),
    ],
    "03.26": [
        q(
            "Explain phase-contrast encoding.",
            "What physical measurement provides contrast in phase-contrast MRA?",
            "A velocity-dependent phase shift created by bipolar gradients",
            [
                "A T1 reduction caused by gadolinium",
                "A proton-density difference between blood and tissue only",
                "A frequency offset caused by fat shielding",
            ],
            "Bipolar gradients cancel phase in stationary spins but leave a phase shift in moving spins. The magnitude and sign of that shift encode velocity along the selected direction.",
        ),
        q(
            "Explain phase subtraction.",
            "Why are flow-encoded and reference acquisitions compared in phase-contrast imaging?",
            "Subtracting their phases removes background phase and isolates motion-related phase",
            [
                "Subtracting them creates longitudinal magnetization",
                "The reference acquisition measures only T2 relaxation",
                "The comparison replaces all spatial encoding",
            ],
            "A reference and a velocity-encoded acquisition share many static phase offsets. Their phase difference emphasizes the component caused by moving spins.",
        ),
        q(
            "Define VENC.",
            "What does the selected velocity-encoding value represent?",
            "The maximum unaliased velocity assigned to a phase shift of 180 degrees",
            [
                "The minimum velocity that can ever produce signal",
                "The receiver bandwidth expressed in centimeters per second",
                "The average tissue T1 within the vessel",
            ],
            "VENC sets the relationship between velocity and phase. Velocities at or beyond the encoded range can wrap in phase, analogous to aliasing.",
        ),
        q(
            "Recognize low-VENC error.",
            "What happens when VENC is set below the highest velocity in a vessel?",
            "Velocity aliasing occurs",
            [
                "Slow-flow sensitivity disappears without aliasing",
                "All stationary tissue becomes bright from inflow",
                "Gadolinium concentration is underestimated",
            ],
            "Velocities exceeding the encoded range cross the phase boundary and are displayed with an incorrect magnitude or direction. Raising VENC removes the wrap but reduces sensitivity to slow flow.",
        ),
        q(
            "Recognize high-VENC tradeoff.",
            "What is the disadvantage of setting VENC much higher than the velocities of interest?",
            "Small velocity differences produce very small phase shifts and are measured less sensitively",
            [
                "Fast flow aliases more severely",
                "Stationary tissue acquires a 180-degree phase shift",
                "The sequence becomes contrast-enhanced automatically",
            ],
            "High VENC reserves the phase range for high speeds, compressing slow velocities into a narrow phase interval. Noise then has a larger effect on low-flow measurement.",
        ),
        q(
            "Identify phase-contrast capability.",
            "What capability distinguishes phase-contrast MRA from basic TOF MRA?",
            "It can quantify velocity and flow direction",
            [
                "It requires no gradients",
                "It images only stationary tissue",
                "It cannot acquire magnitude information",
            ],
            "The velocity-dependent phase signal can be calibrated to measure speed, direction, and volumetric flow. TOF primarily exploits inflow enhancement and is usually qualitative.",
        ),
    ],
    "03.27": [
        q(
            "Explain gadolinium vessel signal.",
            "Why does gadolinium-enhanced blood appear bright on a T1-weighted MR angiographic acquisition?",
            "Gadolinium shortens blood T1 so longitudinal magnetization recovers rapidly",
            [
                "Gadolinium eliminates hydrogen precession",
                "Gadolinium lengthens blood T1 beyond stationary tissue",
                "Gadolinium creates a velocity-dependent phase shift without RF",
            ],
            "A gadolinium chelate increases longitudinal relaxation rate, allowing blood to generate strong signal during a rapid T1-weighted gradient echo. This mechanism is distinct from TOF inflow enhancement.",
        ),
        q(
            "Recognize CE-MRA advantage.",
            "Compared with TOF, what is an advantage of contrast-enhanced MRA?",
            "Vessel signal is less dependent on flow direction and repeated-pulse saturation",
            [
                "It requires no attention to acquisition timing",
                "It provides no venous signal under any circumstance",
                "It quantitatively measures velocity from phase alone",
            ],
            "Contrast shortens blood T1 throughout the imaged volume, so slow or in-plane flow can remain bright. The acquisition still requires careful timing to capture the desired vascular phase.",
        ),
        q(
            "Explain bolus timing.",
            "What is the main consequence of starting an arterial contrast-enhanced MRA acquisition too late?",
            "Venous enhancement may contaminate the arterial image",
            [
                "The main magnet loses superconductivity",
                "All gadolinium becomes invisible before reaching vessels",
                "Phase-encoding gradients reverse blood flow",
            ],
            "After the arterial peak, contrast returns through the venous system and reduces arterial-to-venous separation. Timing central k-space near peak arterial enhancement is especially important for contrast.",
        ),
        q(
            "Explain subtraction MRA.",
            "What is removed when a precontrast mask is subtracted from a postcontrast angiographic dataset?",
            "Much of the stationary background tissue signal",
            [
                "The contrast-enhanced vessel signal",
                "All motion between the two acquisitions",
                "The receiver noise from both acquisitions",
            ],
            "Background anatomy appears in both datasets and largely cancels, while newly enhanced vessels remain. Patient motion between mask and contrast images can instead cause subtraction artifact.",
        ),
        q(
            "Recognize gadolinium safety.",
            "Which patient factor warrants particular caution when selecting a gadolinium-based contrast agent?",
            "Severe renal dysfunction",
            [
                "A normal glomerular filtration rate",
                "Remote uncomplicated radiography",
                "A low phase-encoding matrix",
            ],
            "Certain gadolinium agents have been associated with nephrogenic systemic fibrosis in severe renal impairment, so renal status and agent choice matter. Modern practice also considers prior reactions and the need for repeated exposure.",
        ),
    ],
    "03.28": [
        q(
            "Distinguish spectroscopy from imaging.",
            "What is the primary output of proton MR spectroscopy?",
            "A spectrum of metabolite signal versus chemical shift",
            [
                "A projection of maximum vessel intensity",
                "A map of only longitudinal recovery times",
                "A radiograph based on x-ray attenuation",
            ],
            "MRS separates resonance frequencies to identify biochemical peaks rather than primarily depicting anatomy. Peak position identifies compounds and peak area relates to relative concentration.",
        ),
        q(
            "Identify common metabolite peaks.",
            "Which metabolite is commonly interpreted as a marker of neuronal integrity in brain proton spectroscopy?",
            "NAA",
            [
                "Choline",
                "Creatine",
                "Lactate",
            ],
            "N-acetylaspartate is concentrated in neurons and axons, so reduced NAA can indicate neuronal loss or dysfunction. Choline reflects membrane turnover, creatine is often a reference, and lactate suggests anaerobic metabolism.",
        ),
        q(
            "Interpret choline.",
            "What does an elevated choline peak most directly suggest?",
            "Increased membrane synthesis or turnover",
            [
                "Improved neuronal integrity",
                "Complete absence of cellular metabolism",
                "Only macroscopic blood flow velocity",
            ],
            "Choline-containing compounds participate in membrane metabolism and often rise with high cellular turnover. The finding is nonspecific but can support active tumor or demyelinating processes in context.",
        ),
        q(
            "Explain water suppression.",
            "Why is water suppression used in proton MR spectroscopy?",
            "The water peak would otherwise overwhelm much smaller metabolite signals",
            [
                "Water contains no hydrogen resonance",
                "Suppressing water increases the main field strength",
                "Metabolites can be measured only after T1 becomes zero",
            ],
            "Tissue water concentration is far greater than metabolite concentration, creating a dominant spectral peak. Selective suppression reveals the much smaller metabolite resonances.",
        ),
        q(
            "Describe PRESS localization.",
            "How does PRESS define a spectroscopy voxel?",
            "Three slice-selective RF pulses applied along orthogonal planes select their intersection",
            [
                "One readout gradient selects the brightest image pixel",
                "A maximum-intensity projection chooses the vessel center",
                "A saturation band measures every voxel outside the anatomy",
            ],
            "PRESS uses a 90-degree pulse followed by two 180-degree pulses with orthogonal slice selection. Signal is refocused only from the volume where all three selected slabs intersect.",
        ),
        q(
            "Explain shimming in spectroscopy.",
            "Why is careful shimming especially important for MR spectroscopy?",
            "A uniform B0 field keeps metabolite peaks narrow and separable",
            [
                "It changes every metabolite into water",
                "It eliminates the need for frequency encoding",
                "It makes chemical shift independent of molecular environment",
            ],
            "Field inhomogeneity broadens resonance lines and can merge nearby metabolite peaks. Good shimming improves spectral resolution and the reliability of peak measurements.",
        ),
    ],
}
