const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const app=path.join(root,'apps/neuroradish-catalog');
const catalog=JSON.parse(fs.readFileSync(path.join(app,'catalog.json'),'utf8'));
const key='radiology-video-library-v2';
const url='http://127.0.0.1:8765/apps/neuroradish-catalog/';
(async()=>{
 assert.equal(catalog.videos.length,721);
 assert.equal(new Set(catalog.videos.map(v=>v.id)).size,721);
 assert.equal(catalog.videos.filter(v=>v.channel==='neuroradish'&&v.format==='Short').length,170);
 for(const v of catalog.videos.filter(v=>v.transcript.status==='saved')) {
   const transcript=JSON.parse(fs.readFileSync(path.join(app,v.transcript.path),'utf8'));
   assert.equal(transcript.video_id,v.id);assert.ok(transcript.text.length>0);
 }
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const context=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage(); const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.locator('[data-channel]').first().waitFor();
 assert.equal(await page.locator('[data-channel]').count(),4);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:path.join(process.env.TEMP,'radiology-channels.png'),fullPage:true});
 await page.locator('[data-channel="neuroradish"]').click();
 await page.locator('[data-format="Short"]').click();
 assert.match(await page.locator('#resultCount').innerText(),/170 lessons/);
 await page.locator('#filterButton').click();await page.locator('#series').selectOption('Buzzword Core Exam');
 assert.match(await page.locator('#resultCount').innerText(),/109 lessons/);
 await page.locator('#startQueue').click();
 const first=await page.locator('#studyTitle').innerText();assert.match(first,/#1\b/);
 await page.locator('#doneNext').click();assert.match(await page.locator('#studyTitle').innerText(),/#2\b/);
 await page.reload();await page.locator('#studyPage').waitFor();assert.match(await page.locator('#studyTitle').innerText(),/#2\b/);
 await page.locator('#backBrowse').click();assert.equal(await page.locator('#series').inputValue(),'Buzzword Core Exam');
 await page.locator('#resumeButton').click();assert.match(await page.locator('#studyTitle').innerText(),/#2\b/);
 await page.evaluate(()=>{window.open=(u)=>{window.openedURL=u;return {opener:null};};});
 await page.locator('#transcriptFallback').click();
 assert.equal(await page.evaluate(()=>window.openedURL),'https://www.youtube-transcript.io/');
 const savedState=JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key));
 assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'https://www.youtube.com/watch?v='+savedState.channels.neuroradish.current);
 await page.locator('summary').filter({hasText:'Transcript text'}).click();
 await page.locator('#transcriptText').fill('Example user-pasted transcript for persistence test.');
 await page.locator('#saveTranscript').click();await page.locator('#copyPrompt').click();
 assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/For each pathology discussed/);
 await page.reload();await page.locator('#copyTranscript').waitFor();
 await page.waitForFunction(()=>!document.getElementById('copyTranscript').disabled);
 assert.match(await page.locator('#transcriptText').inputValue(),/Example user-pasted/);
 await page.screenshot({path:path.join(process.env.TEMP,'radiology-study.png'),fullPage:true});
 // The final lesson must never silently switch to another series.
 await page.evaluate(()=>{const p=state.channels.neuroradish;p.current=p.queue.at(-1);save();});
 await page.reload();await page.locator('#studyPage').waitFor();await page.locator('#doneNext').click();
 await page.locator('#libraryPage').waitFor();assert.equal(await page.locator('#series').inputValue(),'Buzzword Core Exam');
 await page.locator('#backChannels').click();await page.locator('[data-channel="tutorials"]').click();
 await page.locator('#backChannels').click();await page.locator('[data-channel="neuroradish"]').click();
 assert.equal(await page.locator('#series').inputValue(),'Buzzword Core Exam');
 await page.locator('#search').fill('definitely-no-matching-video');
 assert.equal(await page.locator('#startQueue').isDisabled(),true);
 assert.equal(await page.locator('#resumeButton').count(),0);
 await page.locator('#search').fill('');
 // Load an actual checked-in transcript through the UI.
 const available=catalog.videos.find(v=>v.transcript.status==='saved');
 await page.evaluate(v=>{state.channel=v.channel;state.page='study';state.channels[v.channel]={queue:[v.id],current:v.id};save();},available);
 await page.reload();await page.waitForFunction(()=>!document.getElementById('copyTranscript').disabled);
 await page.locator('#copyTranscript').click();assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).length>200);
 // Old arbitrary filters and progress survive migration.
 const oldVideo=catalog.videos.find(v=>catalog.legacy[v.id]?.category==='Buzzword cases');
 const category=oldVideo? 'Buzzword cases':catalog.legacy[catalog.videos.find(v=>v.channel==='neuroradish'&&v.series==='Buzzword Core Exam').id].category;
 await page.addInitScript(({key,category})=>{localStorage.removeItem(key);localStorage.setItem('neuroradish-catalog-v1',JSON.stringify({ui:{view:'all',filters:{category:[category]}}}));},{key,category});
 await page.reload();await page.locator('#libraryPage').waitFor();
 assert.match(await page.locator('#resultCount').innerText(),/109 lessons/);
 await page.locator('#filterButton').click();await page.locator('#sort').selectOption('title');
 assert.match(await page.locator('#resultCount').innerText(),/109 lessons/);
 await page.locator('#backupOpen').click();page.once('dialog',d=>d.accept());
 await page.locator('#importBackup').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,catalog:'neuroradish',state:{ui:{view:'all',filters:{category:[category]}}}}))});
 await page.locator('#backupDialog').waitFor({state:'hidden'});
 assert.match(await page.locator('#resultCount').innerText(),/109 lessons/);
 assert.deepEqual(errors,[]);
 const desktop=await context.newPage();await desktop.setViewportSize({width:1280,height:900});
 await desktop.goto(url);await desktop.locator('#libraryPage').waitFor();
 assert.ok(await desktop.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await desktop.screenshot({path:path.join(process.env.TEMP,'radiology-desktop.png'),fullPage:false});
 await browser.close();console.log('PASS: 721 inventory IDs, 245 transcript files, mobile layout, Shorts, filtered queue, reload, last-item boundary, clipboard, fallback, paste, legacy migration.');
})().catch(e=>{console.error(e);process.exit(1);});
